package com.egdfrm.unit.mapper.standard;

import com.egdfrm.unit.model.standard.CuxOrderLine;
import com.egdfrm.unit.model.standard.CuxOrderLineCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuxOrderLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_LINE
     *
     * @mbggenerated Fri Jan 20 08:32:43 CST 2017
     */
    int countByExample(CuxOrderLineCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_LINE
     *
     * @mbggenerated Fri Jan 20 08:32:43 CST 2017
     */
    int deleteByExample(CuxOrderLineCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_LINE
     *
     * @mbggenerated Fri Jan 20 08:32:43 CST 2017
     */
    int insert(CuxOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_LINE
     *
     * @mbggenerated Fri Jan 20 08:32:43 CST 2017
     */
    int insertSelective(CuxOrderLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_LINE
     *
     * @mbggenerated Fri Jan 20 08:32:43 CST 2017
     */
    List<CuxOrderLine> selectByExample(CuxOrderLineCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_LINE
     *
     * @mbggenerated Fri Jan 20 08:32:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") CuxOrderLine record, @Param("example") CuxOrderLineCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_LINE
     *
     * @mbggenerated Fri Jan 20 08:32:43 CST 2017
     */
    int updateByExample(@Param("record") CuxOrderLine record, @Param("example") CuxOrderLineCriteria example);
}