package com.egdfrm.unit.mapper.standard;

import com.egdfrm.unit.model.standard.CuxOrderHeadeHis;
import com.egdfrm.unit.model.standard.CuxOrderHeadeHisCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CuxOrderHeadeHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE_HIS
     *
     * @mbggenerated Sat Feb 04 09:40:57 CST 2017
     */
    int countByExample(CuxOrderHeadeHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE_HIS
     *
     * @mbggenerated Sat Feb 04 09:40:57 CST 2017
     */
    int deleteByExample(CuxOrderHeadeHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE_HIS
     *
     * @mbggenerated Sat Feb 04 09:40:57 CST 2017
     */
    int insert(CuxOrderHeadeHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE_HIS
     *
     * @mbggenerated Sat Feb 04 09:40:57 CST 2017
     */
    int insertSelective(CuxOrderHeadeHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE_HIS
     *
     * @mbggenerated Sat Feb 04 09:40:57 CST 2017
     */
    List<CuxOrderHeadeHis> selectByExample(CuxOrderHeadeHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE_HIS
     *
     * @mbggenerated Sat Feb 04 09:40:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") CuxOrderHeadeHis record, @Param("example") CuxOrderHeadeHisCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE_HIS
     *
     * @mbggenerated Sat Feb 04 09:40:57 CST 2017
     */
    int updateByExample(@Param("record") CuxOrderHeadeHis record, @Param("example") CuxOrderHeadeHisCriteria example);
}