package com.egdfrm.unit.mapper.standard;

import com.egdfrm.unit.model.standard.MesAfterSale;
import com.egdfrm.unit.model.standard.MesAfterSaleCriteria;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MesAfterSaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int countByExample(MesAfterSaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int deleteByExample(MesAfterSaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int insert(MesAfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int insertSelective(MesAfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    List<MesAfterSale> selectByExample(MesAfterSaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    MesAfterSale selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int updateByExampleSelective(@Param("record") MesAfterSale record, @Param("example") MesAfterSaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int updateByExample(@Param("record") MesAfterSale record, @Param("example") MesAfterSaleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int updateByPrimaryKeySelective(MesAfterSale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    int updateByPrimaryKey(MesAfterSale record);
}