package com.egdfrm.unit.mapper.standard;

import com.egdfrm.unit.model.standard.MesPackingHeaders;
import com.egdfrm.unit.model.standard.MesPackingHeadersCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MesPackingHeadersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    int countByExample(MesPackingHeadersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    int deleteByExample(MesPackingHeadersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    int insert(MesPackingHeaders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    int insertSelective(MesPackingHeaders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    List<MesPackingHeaders> selectByExampleWithBLOBs(MesPackingHeadersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    List<MesPackingHeaders> selectByExample(MesPackingHeadersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") MesPackingHeaders record, @Param("example") MesPackingHeadersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") MesPackingHeaders record, @Param("example") MesPackingHeadersCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_PACKING_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:44:07 CST 2016
     */
    int updateByExample(@Param("record") MesPackingHeaders record, @Param("example") MesPackingHeadersCriteria example);
}