package com.egdfrm.unit.mapper.standard;

import com.egdfrm.unit.model.report.DailyStatistics;
import com.egdfrm.unit.model.standard.MesWipComV;
import com.egdfrm.unit.model.standard.MesWipComVCriteria;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MesWipComVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_WIP_COM_V
     *
     * @mbggenerated Thu Jan 05 18:40:23 CST 2017
     */
    int countByExample(MesWipComVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_WIP_COM_V
     *
     * @mbggenerated Thu Jan 05 18:40:23 CST 2017
     */
    int deleteByExample(MesWipComVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_WIP_COM_V
     *
     * @mbggenerated Thu Jan 05 18:40:23 CST 2017
     */
    int insert(MesWipComV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_WIP_COM_V
     *
     * @mbggenerated Thu Jan 05 18:40:23 CST 2017
     */
    int insertSelective(MesWipComV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_WIP_COM_V
     *
     * @mbggenerated Thu Jan 05 18:40:23 CST 2017
     */
    List<MesWipComV> selectByExample(MesWipComVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_WIP_COM_V
     *
     * @mbggenerated Thu Jan 05 18:40:23 CST 2017
     */
    int updateByExampleSelective(@Param("record") MesWipComV record, @Param("example") MesWipComVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_WIP_COM_V
     *
     * @mbggenerated Thu Jan 05 18:40:23 CST 2017
     */
    int updateByExample(@Param("record") MesWipComV record, @Param("example") MesWipComVCriteria example);

    /**
     * @author sjf
     * @date 2017年1月6日 
     * @param example
     * @return
     * add by sjf 20170106 返回格式为默认LIST map
     */
    List<Map<String, Object>> selectByExampleListMap(MesWipComVCriteria example);

    /**
     * 生产统计日报表_数据查询
     * @param proLine 生产线
     * @param startTime 开始日期
     * @param endTime 结束日期
     * @return 数据集
     */
    List<DailyStatistics> queryDailyStatistics(@Param("proLine") String proLine, @Param("startTime") String startTime, @Param("endTime") String endTime);
}