package com.egdfrm.unit.mapper.standard;

import com.egdfrm.unit.model.standard.MtlSubinventoriesAllV;
import com.egdfrm.unit.model.standard.MtlSubinventoriesAllVCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MtlSubinventoriesAllVMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_SUBINVENTORIES_ALL_V
     *
     * @mbggenerated Thu Jan 05 08:15:35 CST 2017
     */
    int countByExample(MtlSubinventoriesAllVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_SUBINVENTORIES_ALL_V
     *
     * @mbggenerated Thu Jan 05 08:15:35 CST 2017
     */
    int deleteByExample(MtlSubinventoriesAllVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_SUBINVENTORIES_ALL_V
     *
     * @mbggenerated Thu Jan 05 08:15:35 CST 2017
     */
    int insert(MtlSubinventoriesAllV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_SUBINVENTORIES_ALL_V
     *
     * @mbggenerated Thu Jan 05 08:15:35 CST 2017
     */
    int insertSelective(MtlSubinventoriesAllV record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_SUBINVENTORIES_ALL_V
     *
     * @mbggenerated Thu Jan 05 08:15:35 CST 2017
     */
    List<MtlSubinventoriesAllV> selectByExample(MtlSubinventoriesAllVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_SUBINVENTORIES_ALL_V
     *
     * @mbggenerated Thu Jan 05 08:15:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") MtlSubinventoriesAllV record, @Param("example") MtlSubinventoriesAllVCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_SUBINVENTORIES_ALL_V
     *
     * @mbggenerated Thu Jan 05 08:15:35 CST 2017
     */
    int updateByExample(@Param("record") MtlSubinventoriesAllV record, @Param("example") MtlSubinventoriesAllVCriteria example);
}