package com.egdfrm.unit.model.standard;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CuxOrderHeadeCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public CuxOrderHeadeCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCrmOrderNumberIsNull() {
            addCriterion("CRM_ORDER_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberIsNotNull() {
            addCriterion("CRM_ORDER_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberEqualTo(String value) {
            addCriterion("CRM_ORDER_NUMBER =", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberNotEqualTo(String value) {
            addCriterion("CRM_ORDER_NUMBER <>", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberGreaterThan(String value) {
            addCriterion("CRM_ORDER_NUMBER >", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberGreaterThanOrEqualTo(String value) {
            addCriterion("CRM_ORDER_NUMBER >=", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberLessThan(String value) {
            addCriterion("CRM_ORDER_NUMBER <", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberLessThanOrEqualTo(String value) {
            addCriterion("CRM_ORDER_NUMBER <=", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberLike(String value) {
            addCriterion("CRM_ORDER_NUMBER like", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberNotLike(String value) {
            addCriterion("CRM_ORDER_NUMBER not like", value, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberIn(List<String> values) {
            addCriterion("CRM_ORDER_NUMBER in", values, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberNotIn(List<String> values) {
            addCriterion("CRM_ORDER_NUMBER not in", values, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberBetween(String value1, String value2) {
            addCriterion("CRM_ORDER_NUMBER between", value1, value2, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberNotBetween(String value1, String value2) {
            addCriterion("CRM_ORDER_NUMBER not between", value1, value2, "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberIsNull() {
            addCriterion("ERP_ORDER_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberIsNotNull() {
            addCriterion("ERP_ORDER_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberEqualTo(BigDecimal value) {
            addCriterion("ERP_ORDER_NUMBER =", value, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberNotEqualTo(BigDecimal value) {
            addCriterion("ERP_ORDER_NUMBER <>", value, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberGreaterThan(BigDecimal value) {
            addCriterion("ERP_ORDER_NUMBER >", value, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ERP_ORDER_NUMBER >=", value, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberLessThan(BigDecimal value) {
            addCriterion("ERP_ORDER_NUMBER <", value, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ERP_ORDER_NUMBER <=", value, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberIn(List<BigDecimal> values) {
            addCriterion("ERP_ORDER_NUMBER in", values, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberNotIn(List<BigDecimal> values) {
            addCriterion("ERP_ORDER_NUMBER not in", values, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ERP_ORDER_NUMBER between", value1, value2, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErpOrderNumberNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ERP_ORDER_NUMBER not between", value1, value2, "erpOrderNumber");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNull() {
            addCriterion("PROCESS_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNotNull() {
            addCriterion("PROCESS_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusEqualTo(BigDecimal value) {
            addCriterion("PROCESS_STATUS =", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotEqualTo(BigDecimal value) {
            addCriterion("PROCESS_STATUS <>", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThan(BigDecimal value) {
            addCriterion("PROCESS_STATUS >", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESS_STATUS >=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThan(BigDecimal value) {
            addCriterion("PROCESS_STATUS <", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PROCESS_STATUS <=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIn(List<BigDecimal> values) {
            addCriterion("PROCESS_STATUS in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotIn(List<BigDecimal> values) {
            addCriterion("PROCESS_STATUS not in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESS_STATUS between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PROCESS_STATUS not between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andErrMessagesIsNull() {
            addCriterion("ERR_MESSAGES is null");
            return (Criteria) this;
        }

        public Criteria andErrMessagesIsNotNull() {
            addCriterion("ERR_MESSAGES is not null");
            return (Criteria) this;
        }

        public Criteria andErrMessagesEqualTo(String value) {
            addCriterion("ERR_MESSAGES =", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesNotEqualTo(String value) {
            addCriterion("ERR_MESSAGES <>", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesGreaterThan(String value) {
            addCriterion("ERR_MESSAGES >", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesGreaterThanOrEqualTo(String value) {
            addCriterion("ERR_MESSAGES >=", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesLessThan(String value) {
            addCriterion("ERR_MESSAGES <", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesLessThanOrEqualTo(String value) {
            addCriterion("ERR_MESSAGES <=", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesLike(String value) {
            addCriterion("ERR_MESSAGES like", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesNotLike(String value) {
            addCriterion("ERR_MESSAGES not like", value, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesIn(List<String> values) {
            addCriterion("ERR_MESSAGES in", values, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesNotIn(List<String> values) {
            addCriterion("ERR_MESSAGES not in", values, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesBetween(String value1, String value2) {
            addCriterion("ERR_MESSAGES between", value1, value2, "errMessages");
            return (Criteria) this;
        }

        public Criteria andErrMessagesNotBetween(String value1, String value2) {
            addCriterion("ERR_MESSAGES not between", value1, value2, "errMessages");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(BigDecimal value) {
            addCriterion("ORG_ID =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(BigDecimal value) {
            addCriterion("ORG_ID <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(BigDecimal value) {
            addCriterion("ORG_ID >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORG_ID >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(BigDecimal value) {
            addCriterion("ORG_ID <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORG_ID <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<BigDecimal> values) {
            addCriterion("ORG_ID in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<BigDecimal> values) {
            addCriterion("ORG_ID not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORG_ID between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORG_ID not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdIsNull() {
            addCriterion("ORDER_SOURCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdIsNotNull() {
            addCriterion("ORDER_SOURCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdEqualTo(BigDecimal value) {
            addCriterion("ORDER_SOURCE_ID =", value, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdNotEqualTo(BigDecimal value) {
            addCriterion("ORDER_SOURCE_ID <>", value, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdGreaterThan(BigDecimal value) {
            addCriterion("ORDER_SOURCE_ID >", value, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_SOURCE_ID >=", value, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdLessThan(BigDecimal value) {
            addCriterion("ORDER_SOURCE_ID <", value, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ORDER_SOURCE_ID <=", value, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdIn(List<BigDecimal> values) {
            addCriterion("ORDER_SOURCE_ID in", values, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdNotIn(List<BigDecimal> values) {
            addCriterion("ORDER_SOURCE_ID not in", values, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_SOURCE_ID between", value1, value2, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderSourceIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ORDER_SOURCE_ID not between", value1, value2, "orderSourceId");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNull() {
            addCriterion("ORDER_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOrderDateIsNotNull() {
            addCriterion("ORDER_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDateEqualTo(Date value) {
            addCriterion("ORDER_DATE =", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotEqualTo(Date value) {
            addCriterion("ORDER_DATE <>", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThan(Date value) {
            addCriterion("ORDER_DATE >", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateGreaterThanOrEqualTo(Date value) {
            addCriterion("ORDER_DATE >=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThan(Date value) {
            addCriterion("ORDER_DATE <", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateLessThanOrEqualTo(Date value) {
            addCriterion("ORDER_DATE <=", value, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateIn(List<Date> values) {
            addCriterion("ORDER_DATE in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotIn(List<Date> values) {
            addCriterion("ORDER_DATE not in", values, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateBetween(Date value1, Date value2) {
            addCriterion("ORDER_DATE between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderDateNotBetween(Date value1, Date value2) {
            addCriterion("ORDER_DATE not between", value1, value2, "orderDate");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNull() {
            addCriterion("ORDER_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIsNotNull() {
            addCriterion("ORDER_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOrderTypeEqualTo(String value) {
            addCriterion("ORDER_TYPE =", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotEqualTo(String value) {
            addCriterion("ORDER_TYPE <>", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThan(String value) {
            addCriterion("ORDER_TYPE >", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_TYPE >=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThan(String value) {
            addCriterion("ORDER_TYPE <", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLessThanOrEqualTo(String value) {
            addCriterion("ORDER_TYPE <=", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLike(String value) {
            addCriterion("ORDER_TYPE like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotLike(String value) {
            addCriterion("ORDER_TYPE not like", value, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeIn(List<String> values) {
            addCriterion("ORDER_TYPE in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotIn(List<String> values) {
            addCriterion("ORDER_TYPE not in", values, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeBetween(String value1, String value2) {
            addCriterion("ORDER_TYPE between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andOrderTypeNotBetween(String value1, String value2) {
            addCriterion("ORDER_TYPE not between", value1, value2, "orderType");
            return (Criteria) this;
        }

        public Criteria andPriceListIdIsNull() {
            addCriterion("PRICE_LIST_ID is null");
            return (Criteria) this;
        }

        public Criteria andPriceListIdIsNotNull() {
            addCriterion("PRICE_LIST_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPriceListIdEqualTo(BigDecimal value) {
            addCriterion("PRICE_LIST_ID =", value, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdNotEqualTo(BigDecimal value) {
            addCriterion("PRICE_LIST_ID <>", value, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdGreaterThan(BigDecimal value) {
            addCriterion("PRICE_LIST_ID >", value, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE_LIST_ID >=", value, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdLessThan(BigDecimal value) {
            addCriterion("PRICE_LIST_ID <", value, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE_LIST_ID <=", value, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdIn(List<BigDecimal> values) {
            addCriterion("PRICE_LIST_ID in", values, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdNotIn(List<BigDecimal> values) {
            addCriterion("PRICE_LIST_ID not in", values, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE_LIST_ID between", value1, value2, "priceListId");
            return (Criteria) this;
        }

        public Criteria andPriceListIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE_LIST_ID not between", value1, value2, "priceListId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdIsNull() {
            addCriterion("SALESREP_ID is null");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdIsNotNull() {
            addCriterion("SALESREP_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdEqualTo(BigDecimal value) {
            addCriterion("SALESREP_ID =", value, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdNotEqualTo(BigDecimal value) {
            addCriterion("SALESREP_ID <>", value, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdGreaterThan(BigDecimal value) {
            addCriterion("SALESREP_ID >", value, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SALESREP_ID >=", value, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdLessThan(BigDecimal value) {
            addCriterion("SALESREP_ID <", value, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SALESREP_ID <=", value, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdIn(List<BigDecimal> values) {
            addCriterion("SALESREP_ID in", values, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdNotIn(List<BigDecimal> values) {
            addCriterion("SALESREP_ID not in", values, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALESREP_ID between", value1, value2, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSalesrepIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SALESREP_ID not between", value1, value2, "salesrepId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdIsNull() {
            addCriterion("SOLD_TO_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdIsNotNull() {
            addCriterion("SOLD_TO_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdEqualTo(BigDecimal value) {
            addCriterion("SOLD_TO_ORG_ID =", value, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdNotEqualTo(BigDecimal value) {
            addCriterion("SOLD_TO_ORG_ID <>", value, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdGreaterThan(BigDecimal value) {
            addCriterion("SOLD_TO_ORG_ID >", value, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SOLD_TO_ORG_ID >=", value, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdLessThan(BigDecimal value) {
            addCriterion("SOLD_TO_ORG_ID <", value, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SOLD_TO_ORG_ID <=", value, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdIn(List<BigDecimal> values) {
            addCriterion("SOLD_TO_ORG_ID in", values, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdNotIn(List<BigDecimal> values) {
            addCriterion("SOLD_TO_ORG_ID not in", values, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SOLD_TO_ORG_ID between", value1, value2, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldToOrgIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SOLD_TO_ORG_ID not between", value1, value2, "soldToOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdIsNull() {
            addCriterion("SOLD_FROM_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdIsNotNull() {
            addCriterion("SOLD_FROM_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdEqualTo(BigDecimal value) {
            addCriterion("SOLD_FROM_ORG_ID =", value, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdNotEqualTo(BigDecimal value) {
            addCriterion("SOLD_FROM_ORG_ID <>", value, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdGreaterThan(BigDecimal value) {
            addCriterion("SOLD_FROM_ORG_ID >", value, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SOLD_FROM_ORG_ID >=", value, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdLessThan(BigDecimal value) {
            addCriterion("SOLD_FROM_ORG_ID <", value, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SOLD_FROM_ORG_ID <=", value, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdIn(List<BigDecimal> values) {
            addCriterion("SOLD_FROM_ORG_ID in", values, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdNotIn(List<BigDecimal> values) {
            addCriterion("SOLD_FROM_ORG_ID not in", values, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SOLD_FROM_ORG_ID between", value1, value2, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andSoldFromOrgIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SOLD_FROM_ORG_ID not between", value1, value2, "soldFromOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdIsNull() {
            addCriterion("SHIP_TO_ORG_ID is null");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdIsNotNull() {
            addCriterion("SHIP_TO_ORG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdEqualTo(BigDecimal value) {
            addCriterion("SHIP_TO_ORG_ID =", value, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdNotEqualTo(BigDecimal value) {
            addCriterion("SHIP_TO_ORG_ID <>", value, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdGreaterThan(BigDecimal value) {
            addCriterion("SHIP_TO_ORG_ID >", value, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SHIP_TO_ORG_ID >=", value, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdLessThan(BigDecimal value) {
            addCriterion("SHIP_TO_ORG_ID <", value, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SHIP_TO_ORG_ID <=", value, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdIn(List<BigDecimal> values) {
            addCriterion("SHIP_TO_ORG_ID in", values, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdNotIn(List<BigDecimal> values) {
            addCriterion("SHIP_TO_ORG_ID not in", values, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SHIP_TO_ORG_ID between", value1, value2, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andShipToOrgIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SHIP_TO_ORG_ID not between", value1, value2, "shipToOrgId");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeIsNull() {
            addCriterion("TRANSACTIONAL_CURR_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeIsNotNull() {
            addCriterion("TRANSACTIONAL_CURR_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeEqualTo(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE =", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeNotEqualTo(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE <>", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeGreaterThan(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE >", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE >=", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeLessThan(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE <", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeLessThanOrEqualTo(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE <=", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeLike(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE like", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeNotLike(String value) {
            addCriterion("TRANSACTIONAL_CURR_CODE not like", value, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeIn(List<String> values) {
            addCriterion("TRANSACTIONAL_CURR_CODE in", values, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeNotIn(List<String> values) {
            addCriterion("TRANSACTIONAL_CURR_CODE not in", values, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeBetween(String value1, String value2) {
            addCriterion("TRANSACTIONAL_CURR_CODE between", value1, value2, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeNotBetween(String value1, String value2) {
            addCriterion("TRANSACTIONAL_CURR_CODE not between", value1, value2, "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andBookedFlagIsNull() {
            addCriterion("BOOKED_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andBookedFlagIsNotNull() {
            addCriterion("BOOKED_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andBookedFlagEqualTo(String value) {
            addCriterion("BOOKED_FLAG =", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagNotEqualTo(String value) {
            addCriterion("BOOKED_FLAG <>", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagGreaterThan(String value) {
            addCriterion("BOOKED_FLAG >", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagGreaterThanOrEqualTo(String value) {
            addCriterion("BOOKED_FLAG >=", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagLessThan(String value) {
            addCriterion("BOOKED_FLAG <", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagLessThanOrEqualTo(String value) {
            addCriterion("BOOKED_FLAG <=", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagLike(String value) {
            addCriterion("BOOKED_FLAG like", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagNotLike(String value) {
            addCriterion("BOOKED_FLAG not like", value, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagIn(List<String> values) {
            addCriterion("BOOKED_FLAG in", values, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagNotIn(List<String> values) {
            addCriterion("BOOKED_FLAG not in", values, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagBetween(String value1, String value2) {
            addCriterion("BOOKED_FLAG between", value1, value2, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andBookedFlagNotBetween(String value1, String value2) {
            addCriterion("BOOKED_FLAG not between", value1, value2, "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andCustomerPoIsNull() {
            addCriterion("CUSTOMER_PO is null");
            return (Criteria) this;
        }

        public Criteria andCustomerPoIsNotNull() {
            addCriterion("CUSTOMER_PO is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerPoEqualTo(String value) {
            addCriterion("CUSTOMER_PO =", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoNotEqualTo(String value) {
            addCriterion("CUSTOMER_PO <>", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoGreaterThan(String value) {
            addCriterion("CUSTOMER_PO >", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_PO >=", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoLessThan(String value) {
            addCriterion("CUSTOMER_PO <", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoLessThanOrEqualTo(String value) {
            addCriterion("CUSTOMER_PO <=", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoLike(String value) {
            addCriterion("CUSTOMER_PO like", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoNotLike(String value) {
            addCriterion("CUSTOMER_PO not like", value, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoIn(List<String> values) {
            addCriterion("CUSTOMER_PO in", values, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoNotIn(List<String> values) {
            addCriterion("CUSTOMER_PO not in", values, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoBetween(String value1, String value2) {
            addCriterion("CUSTOMER_PO between", value1, value2, "customerPo");
            return (Criteria) this;
        }

        public Criteria andCustomerPoNotBetween(String value1, String value2) {
            addCriterion("CUSTOMER_PO not between", value1, value2, "customerPo");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNull() {
            addCriterion("ATTRIBUTE1 is null");
            return (Criteria) this;
        }

        public Criteria andAttribute1IsNotNull() {
            addCriterion("ATTRIBUTE1 is not null");
            return (Criteria) this;
        }

        public Criteria andAttribute1EqualTo(String value) {
            addCriterion("ATTRIBUTE1 =", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotEqualTo(String value) {
            addCriterion("ATTRIBUTE1 <>", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThan(String value) {
            addCriterion("ATTRIBUTE1 >", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1GreaterThanOrEqualTo(String value) {
            addCriterion("ATTRIBUTE1 >=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThan(String value) {
            addCriterion("ATTRIBUTE1 <", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1LessThanOrEqualTo(String value) {
            addCriterion("ATTRIBUTE1 <=", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Like(String value) {
            addCriterion("ATTRIBUTE1 like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotLike(String value) {
            addCriterion("ATTRIBUTE1 not like", value, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1In(List<String> values) {
            addCriterion("ATTRIBUTE1 in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotIn(List<String> values) {
            addCriterion("ATTRIBUTE1 not in", values, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1Between(String value1, String value2) {
            addCriterion("ATTRIBUTE1 between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andAttribute1NotBetween(String value1, String value2) {
            addCriterion("ATTRIBUTE1 not between", value1, value2, "attribute1");
            return (Criteria) this;
        }

        public Criteria andShipMethodIsNull() {
            addCriterion("SHIP_METHOD is null");
            return (Criteria) this;
        }

        public Criteria andShipMethodIsNotNull() {
            addCriterion("SHIP_METHOD is not null");
            return (Criteria) this;
        }

        public Criteria andShipMethodEqualTo(String value) {
            addCriterion("SHIP_METHOD =", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodNotEqualTo(String value) {
            addCriterion("SHIP_METHOD <>", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodGreaterThan(String value) {
            addCriterion("SHIP_METHOD >", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodGreaterThanOrEqualTo(String value) {
            addCriterion("SHIP_METHOD >=", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodLessThan(String value) {
            addCriterion("SHIP_METHOD <", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodLessThanOrEqualTo(String value) {
            addCriterion("SHIP_METHOD <=", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodLike(String value) {
            addCriterion("SHIP_METHOD like", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodNotLike(String value) {
            addCriterion("SHIP_METHOD not like", value, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodIn(List<String> values) {
            addCriterion("SHIP_METHOD in", values, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodNotIn(List<String> values) {
            addCriterion("SHIP_METHOD not in", values, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodBetween(String value1, String value2) {
            addCriterion("SHIP_METHOD between", value1, value2, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andShipMethodNotBetween(String value1, String value2) {
            addCriterion("SHIP_METHOD not between", value1, value2, "shipMethod");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andContactsNameIsNull() {
            addCriterion("CONTACTS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andContactsNameIsNotNull() {
            addCriterion("CONTACTS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andContactsNameEqualTo(String value) {
            addCriterion("CONTACTS_NAME =", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameNotEqualTo(String value) {
            addCriterion("CONTACTS_NAME <>", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameGreaterThan(String value) {
            addCriterion("CONTACTS_NAME >", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameGreaterThanOrEqualTo(String value) {
            addCriterion("CONTACTS_NAME >=", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameLessThan(String value) {
            addCriterion("CONTACTS_NAME <", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameLessThanOrEqualTo(String value) {
            addCriterion("CONTACTS_NAME <=", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameLike(String value) {
            addCriterion("CONTACTS_NAME like", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameNotLike(String value) {
            addCriterion("CONTACTS_NAME not like", value, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameIn(List<String> values) {
            addCriterion("CONTACTS_NAME in", values, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameNotIn(List<String> values) {
            addCriterion("CONTACTS_NAME not in", values, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameBetween(String value1, String value2) {
            addCriterion("CONTACTS_NAME between", value1, value2, "contactsName");
            return (Criteria) this;
        }

        public Criteria andContactsNameNotBetween(String value1, String value2) {
            addCriterion("CONTACTS_NAME not between", value1, value2, "contactsName");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("PHONE is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("PHONE is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("PHONE =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("PHONE <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("PHONE >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("PHONE >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("PHONE <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("PHONE <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("PHONE like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("PHONE not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("PHONE in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("PHONE not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("PHONE between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("PHONE not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andCrmOrderNumberLikeInsensitive(String value) {
            addCriterion("upper(CRM_ORDER_NUMBER) like", value.toUpperCase(), "crmOrderNumber");
            return (Criteria) this;
        }

        public Criteria andErrMessagesLikeInsensitive(String value) {
            addCriterion("upper(ERR_MESSAGES) like", value.toUpperCase(), "errMessages");
            return (Criteria) this;
        }

        public Criteria andOrderTypeLikeInsensitive(String value) {
            addCriterion("upper(ORDER_TYPE) like", value.toUpperCase(), "orderType");
            return (Criteria) this;
        }

        public Criteria andTransactionalCurrCodeLikeInsensitive(String value) {
            addCriterion("upper(TRANSACTIONAL_CURR_CODE) like", value.toUpperCase(), "transactionalCurrCode");
            return (Criteria) this;
        }

        public Criteria andBookedFlagLikeInsensitive(String value) {
            addCriterion("upper(BOOKED_FLAG) like", value.toUpperCase(), "bookedFlag");
            return (Criteria) this;
        }

        public Criteria andCustomerPoLikeInsensitive(String value) {
            addCriterion("upper(CUSTOMER_PO) like", value.toUpperCase(), "customerPo");
            return (Criteria) this;
        }

        public Criteria andAttribute1LikeInsensitive(String value) {
            addCriterion("upper(ATTRIBUTE1) like", value.toUpperCase(), "attribute1");
            return (Criteria) this;
        }

        public Criteria andShipMethodLikeInsensitive(String value) {
            addCriterion("upper(SHIP_METHOD) like", value.toUpperCase(), "shipMethod");
            return (Criteria) this;
        }

        public Criteria andAddressLikeInsensitive(String value) {
            addCriterion("upper(ADDRESS) like", value.toUpperCase(), "address");
            return (Criteria) this;
        }

        public Criteria andContactsNameLikeInsensitive(String value) {
            addCriterion("upper(CONTACTS_NAME) like", value.toUpperCase(), "contactsName");
            return (Criteria) this;
        }

        public Criteria andPhoneLikeInsensitive(String value) {
            addCriterion("upper(PHONE) like", value.toUpperCase(), "phone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated do_not_delete_during_merge Tue May 02 17:13:36 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CUX_ORDER_HEADE
     *
     * @mbggenerated Tue May 02 17:13:36 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}