package com.egdfrm.unit.model.standard;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MesAfterSale implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.ID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.PRODUCT_BARCODE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String productBarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.MATERIAL_ID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String materialId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.DESCRIPTION
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.PRODUCTION_TIMES
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private Date productionTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.ORDER_DELIVERY_TIMES
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private Date orderDeliveryTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.STATUS
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.RETURN_OPERATOR
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String returnOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.RETURN_OPERATION_TIME
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private Date returnOperationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.DELIVERY_OPERATOR
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String deliveryOperator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.DELIVERY_OPERATION_TIME
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private Date deliveryOperationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.EXPRESS_NO
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String expressNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.PRODUCT_CATEGORY
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String productCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.BARCODEID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String barcodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_AFTER_SALE.WORKORDER
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private String workorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.ID
     *
     * @return the value of MES_AFTER_SALE.ID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.ID
     *
     * @param id the value for MES_AFTER_SALE.ID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.PRODUCT_BARCODE
     *
     * @return the value of MES_AFTER_SALE.PRODUCT_BARCODE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getProductBarcode() {
        return productBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.PRODUCT_BARCODE
     *
     * @param productBarcode the value for MES_AFTER_SALE.PRODUCT_BARCODE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setProductBarcode(String productBarcode) {
        this.productBarcode = productBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.MATERIAL_ID
     *
     * @return the value of MES_AFTER_SALE.MATERIAL_ID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getMaterialId() {
        return materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.MATERIAL_ID
     *
     * @param materialId the value for MES_AFTER_SALE.MATERIAL_ID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setMaterialId(String materialId) {
        this.materialId = materialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.DESCRIPTION
     *
     * @return the value of MES_AFTER_SALE.DESCRIPTION
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.DESCRIPTION
     *
     * @param description the value for MES_AFTER_SALE.DESCRIPTION
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.PRODUCTION_TIMES
     *
     * @return the value of MES_AFTER_SALE.PRODUCTION_TIMES
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public Date getProductionTimes() {
        return productionTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.PRODUCTION_TIMES
     *
     * @param productionTimes the value for MES_AFTER_SALE.PRODUCTION_TIMES
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setProductionTimes(Date productionTimes) {
        this.productionTimes = productionTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.ORDER_DELIVERY_TIMES
     *
     * @return the value of MES_AFTER_SALE.ORDER_DELIVERY_TIMES
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public Date getOrderDeliveryTimes() {
        return orderDeliveryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.ORDER_DELIVERY_TIMES
     *
     * @param orderDeliveryTimes the value for MES_AFTER_SALE.ORDER_DELIVERY_TIMES
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setOrderDeliveryTimes(Date orderDeliveryTimes) {
        this.orderDeliveryTimes = orderDeliveryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.STATUS
     *
     * @return the value of MES_AFTER_SALE.STATUS
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.STATUS
     *
     * @param status the value for MES_AFTER_SALE.STATUS
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.RETURN_OPERATOR
     *
     * @return the value of MES_AFTER_SALE.RETURN_OPERATOR
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getReturnOperator() {
        return returnOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.RETURN_OPERATOR
     *
     * @param returnOperator the value for MES_AFTER_SALE.RETURN_OPERATOR
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setReturnOperator(String returnOperator) {
        this.returnOperator = returnOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.RETURN_OPERATION_TIME
     *
     * @return the value of MES_AFTER_SALE.RETURN_OPERATION_TIME
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public Date getReturnOperationTime() {
        return returnOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.RETURN_OPERATION_TIME
     *
     * @param returnOperationTime the value for MES_AFTER_SALE.RETURN_OPERATION_TIME
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setReturnOperationTime(Date returnOperationTime) {
        this.returnOperationTime = returnOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.DELIVERY_OPERATOR
     *
     * @return the value of MES_AFTER_SALE.DELIVERY_OPERATOR
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getDeliveryOperator() {
        return deliveryOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.DELIVERY_OPERATOR
     *
     * @param deliveryOperator the value for MES_AFTER_SALE.DELIVERY_OPERATOR
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setDeliveryOperator(String deliveryOperator) {
        this.deliveryOperator = deliveryOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.DELIVERY_OPERATION_TIME
     *
     * @return the value of MES_AFTER_SALE.DELIVERY_OPERATION_TIME
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public Date getDeliveryOperationTime() {
        return deliveryOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.DELIVERY_OPERATION_TIME
     *
     * @param deliveryOperationTime the value for MES_AFTER_SALE.DELIVERY_OPERATION_TIME
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setDeliveryOperationTime(Date deliveryOperationTime) {
        this.deliveryOperationTime = deliveryOperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.EXPRESS_NO
     *
     * @return the value of MES_AFTER_SALE.EXPRESS_NO
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getExpressNo() {
        return expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.EXPRESS_NO
     *
     * @param expressNo the value for MES_AFTER_SALE.EXPRESS_NO
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setExpressNo(String expressNo) {
        this.expressNo = expressNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.PRODUCT_CATEGORY
     *
     * @return the value of MES_AFTER_SALE.PRODUCT_CATEGORY
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getProductCategory() {
        return productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.PRODUCT_CATEGORY
     *
     * @param productCategory the value for MES_AFTER_SALE.PRODUCT_CATEGORY
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setProductCategory(String productCategory) {
        this.productCategory = productCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.BARCODEID
     *
     * @return the value of MES_AFTER_SALE.BARCODEID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getBarcodeid() {
        return barcodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.BARCODEID
     *
     * @param barcodeid the value for MES_AFTER_SALE.BARCODEID
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setBarcodeid(String barcodeid) {
        this.barcodeid = barcodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_AFTER_SALE.WORKORDER
     *
     * @return the value of MES_AFTER_SALE.WORKORDER
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getWorkorder() {
        return workorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_AFTER_SALE.WORKORDER
     *
     * @param workorder the value for MES_AFTER_SALE.WORKORDER
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setWorkorder(String workorder) {
        this.workorder = workorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MesAfterSale other = (MesAfterSale) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductBarcode() == null ? other.getProductBarcode() == null : this.getProductBarcode().equals(other.getProductBarcode()))
            && (this.getMaterialId() == null ? other.getMaterialId() == null : this.getMaterialId().equals(other.getMaterialId()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getProductionTimes() == null ? other.getProductionTimes() == null : this.getProductionTimes().equals(other.getProductionTimes()))
            && (this.getOrderDeliveryTimes() == null ? other.getOrderDeliveryTimes() == null : this.getOrderDeliveryTimes().equals(other.getOrderDeliveryTimes()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getReturnOperator() == null ? other.getReturnOperator() == null : this.getReturnOperator().equals(other.getReturnOperator()))
            && (this.getReturnOperationTime() == null ? other.getReturnOperationTime() == null : this.getReturnOperationTime().equals(other.getReturnOperationTime()))
            && (this.getDeliveryOperator() == null ? other.getDeliveryOperator() == null : this.getDeliveryOperator().equals(other.getDeliveryOperator()))
            && (this.getDeliveryOperationTime() == null ? other.getDeliveryOperationTime() == null : this.getDeliveryOperationTime().equals(other.getDeliveryOperationTime()))
            && (this.getExpressNo() == null ? other.getExpressNo() == null : this.getExpressNo().equals(other.getExpressNo()))
            && (this.getProductCategory() == null ? other.getProductCategory() == null : this.getProductCategory().equals(other.getProductCategory()))
            && (this.getBarcodeid() == null ? other.getBarcodeid() == null : this.getBarcodeid().equals(other.getBarcodeid()))
            && (this.getWorkorder() == null ? other.getWorkorder() == null : this.getWorkorder().equals(other.getWorkorder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductBarcode() == null) ? 0 : getProductBarcode().hashCode());
        result = prime * result + ((getMaterialId() == null) ? 0 : getMaterialId().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getProductionTimes() == null) ? 0 : getProductionTimes().hashCode());
        result = prime * result + ((getOrderDeliveryTimes() == null) ? 0 : getOrderDeliveryTimes().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getReturnOperator() == null) ? 0 : getReturnOperator().hashCode());
        result = prime * result + ((getReturnOperationTime() == null) ? 0 : getReturnOperationTime().hashCode());
        result = prime * result + ((getDeliveryOperator() == null) ? 0 : getDeliveryOperator().hashCode());
        result = prime * result + ((getDeliveryOperationTime() == null) ? 0 : getDeliveryOperationTime().hashCode());
        result = prime * result + ((getExpressNo() == null) ? 0 : getExpressNo().hashCode());
        result = prime * result + ((getProductCategory() == null) ? 0 : getProductCategory().hashCode());
        result = prime * result + ((getBarcodeid() == null) ? 0 : getBarcodeid().hashCode());
        result = prime * result + ((getWorkorder() == null) ? 0 : getWorkorder().hashCode());
        return result;
    }
}