package com.egdfrm.unit.model.standard;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MesAfterSaleCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public MesAfterSaleCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeIsNull() {
            addCriterion("PRODUCT_BARCODE is null");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeIsNotNull() {
            addCriterion("PRODUCT_BARCODE is not null");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeEqualTo(String value) {
            addCriterion("PRODUCT_BARCODE =", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeNotEqualTo(String value) {
            addCriterion("PRODUCT_BARCODE <>", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeGreaterThan(String value) {
            addCriterion("PRODUCT_BARCODE >", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_BARCODE >=", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeLessThan(String value) {
            addCriterion("PRODUCT_BARCODE <", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_BARCODE <=", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeLike(String value) {
            addCriterion("PRODUCT_BARCODE like", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeNotLike(String value) {
            addCriterion("PRODUCT_BARCODE not like", value, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeIn(List<String> values) {
            addCriterion("PRODUCT_BARCODE in", values, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeNotIn(List<String> values) {
            addCriterion("PRODUCT_BARCODE not in", values, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeBetween(String value1, String value2) {
            addCriterion("PRODUCT_BARCODE between", value1, value2, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_BARCODE not between", value1, value2, "productBarcode");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIsNull() {
            addCriterion("MATERIAL_ID is null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIsNotNull() {
            addCriterion("MATERIAL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialIdEqualTo(String value) {
            addCriterion("MATERIAL_ID =", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotEqualTo(String value) {
            addCriterion("MATERIAL_ID <>", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThan(String value) {
            addCriterion("MATERIAL_ID >", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdGreaterThanOrEqualTo(String value) {
            addCriterion("MATERIAL_ID >=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThan(String value) {
            addCriterion("MATERIAL_ID <", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLessThanOrEqualTo(String value) {
            addCriterion("MATERIAL_ID <=", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLike(String value) {
            addCriterion("MATERIAL_ID like", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotLike(String value) {
            addCriterion("MATERIAL_ID not like", value, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdIn(List<String> values) {
            addCriterion("MATERIAL_ID in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotIn(List<String> values) {
            addCriterion("MATERIAL_ID not in", values, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdBetween(String value1, String value2) {
            addCriterion("MATERIAL_ID between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andMaterialIdNotBetween(String value1, String value2) {
            addCriterion("MATERIAL_ID not between", value1, value2, "materialId");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andProductionTimesIsNull() {
            addCriterion("PRODUCTION_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andProductionTimesIsNotNull() {
            addCriterion("PRODUCTION_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andProductionTimesEqualTo(Date value) {
            addCriterionForJDBCDate("PRODUCTION_TIMES =", value, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesNotEqualTo(Date value) {
            addCriterionForJDBCDate("PRODUCTION_TIMES <>", value, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesGreaterThan(Date value) {
            addCriterionForJDBCDate("PRODUCTION_TIMES >", value, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PRODUCTION_TIMES >=", value, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesLessThan(Date value) {
            addCriterionForJDBCDate("PRODUCTION_TIMES <", value, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("PRODUCTION_TIMES <=", value, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesIn(List<Date> values) {
            addCriterionForJDBCDate("PRODUCTION_TIMES in", values, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesNotIn(List<Date> values) {
            addCriterionForJDBCDate("PRODUCTION_TIMES not in", values, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PRODUCTION_TIMES between", value1, value2, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andProductionTimesNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("PRODUCTION_TIMES not between", value1, value2, "productionTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesIsNull() {
            addCriterion("ORDER_DELIVERY_TIMES is null");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesIsNotNull() {
            addCriterion("ORDER_DELIVERY_TIMES is not null");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES =", value, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesNotEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES <>", value, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesGreaterThan(Date value) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES >", value, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES >=", value, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesLessThan(Date value) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES <", value, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES <=", value, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES in", values, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesNotIn(List<Date> values) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES not in", values, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES between", value1, value2, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andOrderDeliveryTimesNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("ORDER_DELIVERY_TIMES not between", value1, value2, "orderDeliveryTimes");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorIsNull() {
            addCriterion("RETURN_OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorIsNotNull() {
            addCriterion("RETURN_OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorEqualTo(String value) {
            addCriterion("RETURN_OPERATOR =", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorNotEqualTo(String value) {
            addCriterion("RETURN_OPERATOR <>", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorGreaterThan(String value) {
            addCriterion("RETURN_OPERATOR >", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("RETURN_OPERATOR >=", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorLessThan(String value) {
            addCriterion("RETURN_OPERATOR <", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorLessThanOrEqualTo(String value) {
            addCriterion("RETURN_OPERATOR <=", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorLike(String value) {
            addCriterion("RETURN_OPERATOR like", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorNotLike(String value) {
            addCriterion("RETURN_OPERATOR not like", value, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorIn(List<String> values) {
            addCriterion("RETURN_OPERATOR in", values, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorNotIn(List<String> values) {
            addCriterion("RETURN_OPERATOR not in", values, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorBetween(String value1, String value2) {
            addCriterion("RETURN_OPERATOR between", value1, value2, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorNotBetween(String value1, String value2) {
            addCriterion("RETURN_OPERATOR not between", value1, value2, "returnOperator");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeIsNull() {
            addCriterion("RETURN_OPERATION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeIsNotNull() {
            addCriterion("RETURN_OPERATION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeEqualTo(Date value) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME =", value, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME <>", value, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME >", value, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME >=", value, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeLessThan(Date value) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME <", value, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME <=", value, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeIn(List<Date> values) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME in", values, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME not in", values, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME between", value1, value2, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andReturnOperationTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("RETURN_OPERATION_TIME not between", value1, value2, "returnOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorIsNull() {
            addCriterion("DELIVERY_OPERATOR is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorIsNotNull() {
            addCriterion("DELIVERY_OPERATOR is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorEqualTo(String value) {
            addCriterion("DELIVERY_OPERATOR =", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorNotEqualTo(String value) {
            addCriterion("DELIVERY_OPERATOR <>", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorGreaterThan(String value) {
            addCriterion("DELIVERY_OPERATOR >", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("DELIVERY_OPERATOR >=", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorLessThan(String value) {
            addCriterion("DELIVERY_OPERATOR <", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorLessThanOrEqualTo(String value) {
            addCriterion("DELIVERY_OPERATOR <=", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorLike(String value) {
            addCriterion("DELIVERY_OPERATOR like", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorNotLike(String value) {
            addCriterion("DELIVERY_OPERATOR not like", value, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorIn(List<String> values) {
            addCriterion("DELIVERY_OPERATOR in", values, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorNotIn(List<String> values) {
            addCriterion("DELIVERY_OPERATOR not in", values, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorBetween(String value1, String value2) {
            addCriterion("DELIVERY_OPERATOR between", value1, value2, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorNotBetween(String value1, String value2) {
            addCriterion("DELIVERY_OPERATOR not between", value1, value2, "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeIsNull() {
            addCriterion("DELIVERY_OPERATION_TIME is null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeIsNotNull() {
            addCriterion("DELIVERY_OPERATION_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeEqualTo(Date value) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME =", value, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME <>", value, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME >", value, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME >=", value, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeLessThan(Date value) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME <", value, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME <=", value, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeIn(List<Date> values) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME in", values, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME not in", values, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME between", value1, value2, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperationTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("DELIVERY_OPERATION_TIME not between", value1, value2, "deliveryOperationTime");
            return (Criteria) this;
        }

        public Criteria andExpressNoIsNull() {
            addCriterion("EXPRESS_NO is null");
            return (Criteria) this;
        }

        public Criteria andExpressNoIsNotNull() {
            addCriterion("EXPRESS_NO is not null");
            return (Criteria) this;
        }

        public Criteria andExpressNoEqualTo(String value) {
            addCriterion("EXPRESS_NO =", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoNotEqualTo(String value) {
            addCriterion("EXPRESS_NO <>", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoGreaterThan(String value) {
            addCriterion("EXPRESS_NO >", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoGreaterThanOrEqualTo(String value) {
            addCriterion("EXPRESS_NO >=", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoLessThan(String value) {
            addCriterion("EXPRESS_NO <", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoLessThanOrEqualTo(String value) {
            addCriterion("EXPRESS_NO <=", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoLike(String value) {
            addCriterion("EXPRESS_NO like", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoNotLike(String value) {
            addCriterion("EXPRESS_NO not like", value, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoIn(List<String> values) {
            addCriterion("EXPRESS_NO in", values, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoNotIn(List<String> values) {
            addCriterion("EXPRESS_NO not in", values, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoBetween(String value1, String value2) {
            addCriterion("EXPRESS_NO between", value1, value2, "expressNo");
            return (Criteria) this;
        }

        public Criteria andExpressNoNotBetween(String value1, String value2) {
            addCriterion("EXPRESS_NO not between", value1, value2, "expressNo");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIsNull() {
            addCriterion("PRODUCT_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIsNotNull() {
            addCriterion("PRODUCT_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryEqualTo(String value) {
            addCriterion("PRODUCT_CATEGORY =", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotEqualTo(String value) {
            addCriterion("PRODUCT_CATEGORY <>", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryGreaterThan(String value) {
            addCriterion("PRODUCT_CATEGORY >", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT_CATEGORY >=", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLessThan(String value) {
            addCriterion("PRODUCT_CATEGORY <", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT_CATEGORY <=", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLike(String value) {
            addCriterion("PRODUCT_CATEGORY like", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotLike(String value) {
            addCriterion("PRODUCT_CATEGORY not like", value, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryIn(List<String> values) {
            addCriterion("PRODUCT_CATEGORY in", values, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotIn(List<String> values) {
            addCriterion("PRODUCT_CATEGORY not in", values, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryBetween(String value1, String value2) {
            addCriterion("PRODUCT_CATEGORY between", value1, value2, "productCategory");
            return (Criteria) this;
        }

        public Criteria andProductCategoryNotBetween(String value1, String value2) {
            addCriterion("PRODUCT_CATEGORY not between", value1, value2, "productCategory");
            return (Criteria) this;
        }

        public Criteria andBarcodeidIsNull() {
            addCriterion("BARCODEID is null");
            return (Criteria) this;
        }

        public Criteria andBarcodeidIsNotNull() {
            addCriterion("BARCODEID is not null");
            return (Criteria) this;
        }

        public Criteria andBarcodeidEqualTo(String value) {
            addCriterion("BARCODEID =", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidNotEqualTo(String value) {
            addCriterion("BARCODEID <>", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidGreaterThan(String value) {
            addCriterion("BARCODEID >", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidGreaterThanOrEqualTo(String value) {
            addCriterion("BARCODEID >=", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidLessThan(String value) {
            addCriterion("BARCODEID <", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidLessThanOrEqualTo(String value) {
            addCriterion("BARCODEID <=", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidLike(String value) {
            addCriterion("BARCODEID like", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidNotLike(String value) {
            addCriterion("BARCODEID not like", value, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidIn(List<String> values) {
            addCriterion("BARCODEID in", values, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidNotIn(List<String> values) {
            addCriterion("BARCODEID not in", values, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidBetween(String value1, String value2) {
            addCriterion("BARCODEID between", value1, value2, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andBarcodeidNotBetween(String value1, String value2) {
            addCriterion("BARCODEID not between", value1, value2, "barcodeid");
            return (Criteria) this;
        }

        public Criteria andWorkorderIsNull() {
            addCriterion("WORKORDER is null");
            return (Criteria) this;
        }

        public Criteria andWorkorderIsNotNull() {
            addCriterion("WORKORDER is not null");
            return (Criteria) this;
        }

        public Criteria andWorkorderEqualTo(String value) {
            addCriterion("WORKORDER =", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderNotEqualTo(String value) {
            addCriterion("WORKORDER <>", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderGreaterThan(String value) {
            addCriterion("WORKORDER >", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderGreaterThanOrEqualTo(String value) {
            addCriterion("WORKORDER >=", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderLessThan(String value) {
            addCriterion("WORKORDER <", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderLessThanOrEqualTo(String value) {
            addCriterion("WORKORDER <=", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderLike(String value) {
            addCriterion("WORKORDER like", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderNotLike(String value) {
            addCriterion("WORKORDER not like", value, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderIn(List<String> values) {
            addCriterion("WORKORDER in", values, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderNotIn(List<String> values) {
            addCriterion("WORKORDER not in", values, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderBetween(String value1, String value2) {
            addCriterion("WORKORDER between", value1, value2, "workorder");
            return (Criteria) this;
        }

        public Criteria andWorkorderNotBetween(String value1, String value2) {
            addCriterion("WORKORDER not between", value1, value2, "workorder");
            return (Criteria) this;
        }

        public Criteria andProductBarcodeLikeInsensitive(String value) {
            addCriterion("upper(PRODUCT_BARCODE) like", value.toUpperCase(), "productBarcode");
            return (Criteria) this;
        }

        public Criteria andMaterialIdLikeInsensitive(String value) {
            addCriterion("upper(MATERIAL_ID) like", value.toUpperCase(), "materialId");
            return (Criteria) this;
        }

        public Criteria andDescriptionLikeInsensitive(String value) {
            addCriterion("upper(DESCRIPTION) like", value.toUpperCase(), "description");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(STATUS) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andReturnOperatorLikeInsensitive(String value) {
            addCriterion("upper(RETURN_OPERATOR) like", value.toUpperCase(), "returnOperator");
            return (Criteria) this;
        }

        public Criteria andDeliveryOperatorLikeInsensitive(String value) {
            addCriterion("upper(DELIVERY_OPERATOR) like", value.toUpperCase(), "deliveryOperator");
            return (Criteria) this;
        }

        public Criteria andExpressNoLikeInsensitive(String value) {
            addCriterion("upper(EXPRESS_NO) like", value.toUpperCase(), "expressNo");
            return (Criteria) this;
        }

        public Criteria andProductCategoryLikeInsensitive(String value) {
            addCriterion("upper(PRODUCT_CATEGORY) like", value.toUpperCase(), "productCategory");
            return (Criteria) this;
        }

        public Criteria andBarcodeidLikeInsensitive(String value) {
            addCriterion("upper(BARCODEID) like", value.toUpperCase(), "barcodeid");
            return (Criteria) this;
        }

        public Criteria andWorkorderLikeInsensitive(String value) {
            addCriterion("upper(WORKORDER) like", value.toUpperCase(), "workorder");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated do_not_delete_during_merge Wed Dec 21 09:03:24 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MES_AFTER_SALE
     *
     * @mbggenerated Wed Dec 21 09:03:24 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}