package com.egdfrm.unit.model.standard;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MesTransactionsInterface implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.PROCESS_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.ORGANIZATION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_TYPE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.SOURCE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.SOURCE_LINE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal sourceLineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.PACKING_TYPE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String packingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.PACKING_BARCODE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal packingBarcodeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.BARCODE_TEXT
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String barcodeText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.INVENTORY_ITEM_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal inventoryItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private Date transactionDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.QUANTITY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.STATUS_FLAG
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String statusFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String subinventoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.LOCATTION_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String locattionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_SUBINVENTORY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String transferSubinventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_ORGANIZATION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal transferOrganizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_LOCATOR
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String transferLocator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.PROCESS_FLAG
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String processFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.PROCESS_MASSAGE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String processMassage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.CREATION_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.CREATED_BY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private BigDecimal createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.SOURCE_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_REFERENCE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private String transactionReference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MES_TRANSACTIONS_INTERFACE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.PROCESS_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.PROCESS_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.PROCESS_ID
     *
     * @param processId the value for MES_TRANSACTIONS_INTERFACE.PROCESS_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setProcessId(BigDecimal processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.TRANSACTION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_ID
     *
     * @param transactionId the value for MES_TRANSACTIONS_INTERFACE.TRANSACTION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setTransactionId(BigDecimal transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.ORGANIZATION_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.ORGANIZATION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.ORGANIZATION_ID
     *
     * @param organizationId the value for MES_TRANSACTIONS_INTERFACE.ORGANIZATION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setOrganizationId(BigDecimal organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_TYPE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.TRANSACTION_TYPE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_TYPE
     *
     * @param transactionType the value for MES_TRANSACTIONS_INTERFACE.TRANSACTION_TYPE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.SOURCE_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.SOURCE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.SOURCE_ID
     *
     * @param sourceId the value for MES_TRANSACTIONS_INTERFACE.SOURCE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setSourceId(BigDecimal sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.SOURCE_LINE_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.SOURCE_LINE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getSourceLineId() {
        return sourceLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.SOURCE_LINE_ID
     *
     * @param sourceLineId the value for MES_TRANSACTIONS_INTERFACE.SOURCE_LINE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setSourceLineId(BigDecimal sourceLineId) {
        this.sourceLineId = sourceLineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.PACKING_TYPE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.PACKING_TYPE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getPackingType() {
        return packingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.PACKING_TYPE
     *
     * @param packingType the value for MES_TRANSACTIONS_INTERFACE.PACKING_TYPE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setPackingType(String packingType) {
        this.packingType = packingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.PACKING_BARCODE_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.PACKING_BARCODE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getPackingBarcodeId() {
        return packingBarcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.PACKING_BARCODE_ID
     *
     * @param packingBarcodeId the value for MES_TRANSACTIONS_INTERFACE.PACKING_BARCODE_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setPackingBarcodeId(BigDecimal packingBarcodeId) {
        this.packingBarcodeId = packingBarcodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.BARCODE_TEXT
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.BARCODE_TEXT
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getBarcodeText() {
        return barcodeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.BARCODE_TEXT
     *
     * @param barcodeText the value for MES_TRANSACTIONS_INTERFACE.BARCODE_TEXT
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setBarcodeText(String barcodeText) {
        this.barcodeText = barcodeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.INVENTORY_ITEM_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.INVENTORY_ITEM_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getInventoryItemId() {
        return inventoryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.INVENTORY_ITEM_ID
     *
     * @param inventoryItemId the value for MES_TRANSACTIONS_INTERFACE.INVENTORY_ITEM_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setInventoryItemId(BigDecimal inventoryItemId) {
        this.inventoryItemId = inventoryItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_DATE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.TRANSACTION_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public Date getTransactionDate() {
        return transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_DATE
     *
     * @param transactionDate the value for MES_TRANSACTIONS_INTERFACE.TRANSACTION_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.QUANTITY
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.QUANTITY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.QUANTITY
     *
     * @param quantity the value for MES_TRANSACTIONS_INTERFACE.QUANTITY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.STATUS_FLAG
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.STATUS_FLAG
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getStatusFlag() {
        return statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.STATUS_FLAG
     *
     * @param statusFlag the value for MES_TRANSACTIONS_INTERFACE.STATUS_FLAG
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setStatusFlag(String statusFlag) {
        this.statusFlag = statusFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.SUBINVENTORY_CODE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getSubinventoryCode() {
        return subinventoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.SUBINVENTORY_CODE
     *
     * @param subinventoryCode the value for MES_TRANSACTIONS_INTERFACE.SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setSubinventoryCode(String subinventoryCode) {
        this.subinventoryCode = subinventoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.LOCATTION_CODE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.LOCATTION_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getLocattionCode() {
        return locattionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.LOCATTION_CODE
     *
     * @param locattionCode the value for MES_TRANSACTIONS_INTERFACE.LOCATTION_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setLocattionCode(String locattionCode) {
        this.locattionCode = locattionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_SUBINVENTORY
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.TRANSFER_SUBINVENTORY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getTransferSubinventory() {
        return transferSubinventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_SUBINVENTORY
     *
     * @param transferSubinventory the value for MES_TRANSACTIONS_INTERFACE.TRANSFER_SUBINVENTORY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setTransferSubinventory(String transferSubinventory) {
        this.transferSubinventory = transferSubinventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_ORGANIZATION_ID
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.TRANSFER_ORGANIZATION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getTransferOrganizationId() {
        return transferOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_ORGANIZATION_ID
     *
     * @param transferOrganizationId the value for MES_TRANSACTIONS_INTERFACE.TRANSFER_ORGANIZATION_ID
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setTransferOrganizationId(BigDecimal transferOrganizationId) {
        this.transferOrganizationId = transferOrganizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_LOCATOR
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.TRANSFER_LOCATOR
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getTransferLocator() {
        return transferLocator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSFER_LOCATOR
     *
     * @param transferLocator the value for MES_TRANSACTIONS_INTERFACE.TRANSFER_LOCATOR
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setTransferLocator(String transferLocator) {
        this.transferLocator = transferLocator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.PROCESS_FLAG
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.PROCESS_FLAG
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getProcessFlag() {
        return processFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.PROCESS_FLAG
     *
     * @param processFlag the value for MES_TRANSACTIONS_INTERFACE.PROCESS_FLAG
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setProcessFlag(String processFlag) {
        this.processFlag = processFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.PROCESS_MASSAGE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.PROCESS_MASSAGE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getProcessMassage() {
        return processMassage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.PROCESS_MASSAGE
     *
     * @param processMassage the value for MES_TRANSACTIONS_INTERFACE.PROCESS_MASSAGE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setProcessMassage(String processMassage) {
        this.processMassage = processMassage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.LAST_UPDATE_DATE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for MES_TRANSACTIONS_INTERFACE.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.LAST_UPDATED_BY
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for MES_TRANSACTIONS_INTERFACE.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setLastUpdatedBy(BigDecimal lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.CREATION_DATE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.CREATION_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.CREATION_DATE
     *
     * @param creationDate the value for MES_TRANSACTIONS_INTERFACE.CREATION_DATE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.CREATED_BY
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.CREATED_BY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public BigDecimal getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.CREATED_BY
     *
     * @param createdBy the value for MES_TRANSACTIONS_INTERFACE.CREATED_BY
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setCreatedBy(BigDecimal createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.SOURCE_CODE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.SOURCE_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.SOURCE_CODE
     *
     * @param sourceCode the value for MES_TRANSACTIONS_INTERFACE.SOURCE_CODE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_REFERENCE
     *
     * @return the value of MES_TRANSACTIONS_INTERFACE.TRANSACTION_REFERENCE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public String getTransactionReference() {
        return transactionReference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MES_TRANSACTIONS_INTERFACE.TRANSACTION_REFERENCE
     *
     * @param transactionReference the value for MES_TRANSACTIONS_INTERFACE.TRANSACTION_REFERENCE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    public void setTransactionReference(String transactionReference) {
        this.transactionReference = transactionReference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_TRANSACTIONS_INTERFACE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MesTransactionsInterface other = (MesTransactionsInterface) that;
        return (this.getProcessId() == null ? other.getProcessId() == null : this.getProcessId().equals(other.getProcessId()))
            && (this.getTransactionId() == null ? other.getTransactionId() == null : this.getTransactionId().equals(other.getTransactionId()))
            && (this.getOrganizationId() == null ? other.getOrganizationId() == null : this.getOrganizationId().equals(other.getOrganizationId()))
            && (this.getTransactionType() == null ? other.getTransactionType() == null : this.getTransactionType().equals(other.getTransactionType()))
            && (this.getSourceId() == null ? other.getSourceId() == null : this.getSourceId().equals(other.getSourceId()))
            && (this.getSourceLineId() == null ? other.getSourceLineId() == null : this.getSourceLineId().equals(other.getSourceLineId()))
            && (this.getPackingType() == null ? other.getPackingType() == null : this.getPackingType().equals(other.getPackingType()))
            && (this.getPackingBarcodeId() == null ? other.getPackingBarcodeId() == null : this.getPackingBarcodeId().equals(other.getPackingBarcodeId()))
            && (this.getBarcodeText() == null ? other.getBarcodeText() == null : this.getBarcodeText().equals(other.getBarcodeText()))
            && (this.getInventoryItemId() == null ? other.getInventoryItemId() == null : this.getInventoryItemId().equals(other.getInventoryItemId()))
            && (this.getTransactionDate() == null ? other.getTransactionDate() == null : this.getTransactionDate().equals(other.getTransactionDate()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getStatusFlag() == null ? other.getStatusFlag() == null : this.getStatusFlag().equals(other.getStatusFlag()))
            && (this.getSubinventoryCode() == null ? other.getSubinventoryCode() == null : this.getSubinventoryCode().equals(other.getSubinventoryCode()))
            && (this.getLocattionCode() == null ? other.getLocattionCode() == null : this.getLocattionCode().equals(other.getLocattionCode()))
            && (this.getTransferSubinventory() == null ? other.getTransferSubinventory() == null : this.getTransferSubinventory().equals(other.getTransferSubinventory()))
            && (this.getTransferOrganizationId() == null ? other.getTransferOrganizationId() == null : this.getTransferOrganizationId().equals(other.getTransferOrganizationId()))
            && (this.getTransferLocator() == null ? other.getTransferLocator() == null : this.getTransferLocator().equals(other.getTransferLocator()))
            && (this.getProcessFlag() == null ? other.getProcessFlag() == null : this.getProcessFlag().equals(other.getProcessFlag()))
            && (this.getProcessMassage() == null ? other.getProcessMassage() == null : this.getProcessMassage().equals(other.getProcessMassage()))
            && (this.getLastUpdateDate() == null ? other.getLastUpdateDate() == null : this.getLastUpdateDate().equals(other.getLastUpdateDate()))
            && (this.getLastUpdatedBy() == null ? other.getLastUpdatedBy() == null : this.getLastUpdatedBy().equals(other.getLastUpdatedBy()))
            && (this.getCreationDate() == null ? other.getCreationDate() == null : this.getCreationDate().equals(other.getCreationDate()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getSourceCode() == null ? other.getSourceCode() == null : this.getSourceCode().equals(other.getSourceCode()))
            && (this.getTransactionReference() == null ? other.getTransactionReference() == null : this.getTransactionReference().equals(other.getTransactionReference()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MES_TRANSACTIONS_INTERFACE
     *
     * @mbggenerated Thu Jan 12 13:59:33 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProcessId() == null) ? 0 : getProcessId().hashCode());
        result = prime * result + ((getTransactionId() == null) ? 0 : getTransactionId().hashCode());
        result = prime * result + ((getOrganizationId() == null) ? 0 : getOrganizationId().hashCode());
        result = prime * result + ((getTransactionType() == null) ? 0 : getTransactionType().hashCode());
        result = prime * result + ((getSourceId() == null) ? 0 : getSourceId().hashCode());
        result = prime * result + ((getSourceLineId() == null) ? 0 : getSourceLineId().hashCode());
        result = prime * result + ((getPackingType() == null) ? 0 : getPackingType().hashCode());
        result = prime * result + ((getPackingBarcodeId() == null) ? 0 : getPackingBarcodeId().hashCode());
        result = prime * result + ((getBarcodeText() == null) ? 0 : getBarcodeText().hashCode());
        result = prime * result + ((getInventoryItemId() == null) ? 0 : getInventoryItemId().hashCode());
        result = prime * result + ((getTransactionDate() == null) ? 0 : getTransactionDate().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getStatusFlag() == null) ? 0 : getStatusFlag().hashCode());
        result = prime * result + ((getSubinventoryCode() == null) ? 0 : getSubinventoryCode().hashCode());
        result = prime * result + ((getLocattionCode() == null) ? 0 : getLocattionCode().hashCode());
        result = prime * result + ((getTransferSubinventory() == null) ? 0 : getTransferSubinventory().hashCode());
        result = prime * result + ((getTransferOrganizationId() == null) ? 0 : getTransferOrganizationId().hashCode());
        result = prime * result + ((getTransferLocator() == null) ? 0 : getTransferLocator().hashCode());
        result = prime * result + ((getProcessFlag() == null) ? 0 : getProcessFlag().hashCode());
        result = prime * result + ((getProcessMassage() == null) ? 0 : getProcessMassage().hashCode());
        result = prime * result + ((getLastUpdateDate() == null) ? 0 : getLastUpdateDate().hashCode());
        result = prime * result + ((getLastUpdatedBy() == null) ? 0 : getLastUpdatedBy().hashCode());
        result = prime * result + ((getCreationDate() == null) ? 0 : getCreationDate().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getSourceCode() == null) ? 0 : getSourceCode().hashCode());
        result = prime * result + ((getTransactionReference() == null) ? 0 : getTransactionReference().hashCode());
        return result;
    }
}