package com.egdfrm.unit.model.standard;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class MtlTxnRequestHeaders implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.HEADER_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal headerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.REQUEST_NUMBER
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String requestNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.TRANSACTION_TYPE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal transactionTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.MOVE_ORDER_TYPE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal moveOrderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ORGANIZATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal organizationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.DESCRIPTION
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.DATE_REQUIRED
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private Date dateRequired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.FROM_SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String fromSubinventoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.TO_SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String toSubinventoryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.TO_ACCOUNT_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal toAccountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.HEADER_STATUS
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal headerStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.STATUS_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private Date statusDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal lastUpdatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_LOGIN
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal lastUpdateLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.CREATED_BY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.CREATION_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private Date creationDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.REQUEST_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal requestId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_APPLICATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal programApplicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal programId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_UPDATE_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private Date programUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.GROUPING_RULE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal groupingRuleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE1
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE2
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE3
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE4
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE5
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE6
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE7
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute7;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE8
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute8;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE9
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute9;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE10
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute10;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE11
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute11;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE12
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute12;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE13
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute13;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE14
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute14;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE15
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attribute15;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE_CATEGORY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String attributeCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.SHIP_TO_LOCATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal shipToLocationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.FREIGHT_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String freightCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.SHIPMENT_METHOD
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String shipmentMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.AUTO_RECEIPT_FLAG
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String autoReceiptFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.REFERENCE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal referenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.REFERENCE_DETAIL_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private BigDecimal referenceDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MTL_TXN_REQUEST_HEADERS.ASSIGNMENT_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private String assignmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MTL_TXN_REQUEST_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.HEADER_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.HEADER_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getHeaderId() {
        return headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.HEADER_ID
     *
     * @param headerId the value for MTL_TXN_REQUEST_HEADERS.HEADER_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setHeaderId(BigDecimal headerId) {
        this.headerId = headerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.REQUEST_NUMBER
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.REQUEST_NUMBER
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getRequestNumber() {
        return requestNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.REQUEST_NUMBER
     *
     * @param requestNumber the value for MTL_TXN_REQUEST_HEADERS.REQUEST_NUMBER
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setRequestNumber(String requestNumber) {
        this.requestNumber = requestNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.TRANSACTION_TYPE_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.TRANSACTION_TYPE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getTransactionTypeId() {
        return transactionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.TRANSACTION_TYPE_ID
     *
     * @param transactionTypeId the value for MTL_TXN_REQUEST_HEADERS.TRANSACTION_TYPE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setTransactionTypeId(BigDecimal transactionTypeId) {
        this.transactionTypeId = transactionTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.MOVE_ORDER_TYPE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.MOVE_ORDER_TYPE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getMoveOrderType() {
        return moveOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.MOVE_ORDER_TYPE
     *
     * @param moveOrderType the value for MTL_TXN_REQUEST_HEADERS.MOVE_ORDER_TYPE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setMoveOrderType(BigDecimal moveOrderType) {
        this.moveOrderType = moveOrderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ORGANIZATION_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ORGANIZATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ORGANIZATION_ID
     *
     * @param organizationId the value for MTL_TXN_REQUEST_HEADERS.ORGANIZATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setOrganizationId(BigDecimal organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.DESCRIPTION
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.DESCRIPTION
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.DESCRIPTION
     *
     * @param description the value for MTL_TXN_REQUEST_HEADERS.DESCRIPTION
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.DATE_REQUIRED
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.DATE_REQUIRED
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public Date getDateRequired() {
        return dateRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.DATE_REQUIRED
     *
     * @param dateRequired the value for MTL_TXN_REQUEST_HEADERS.DATE_REQUIRED
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setDateRequired(Date dateRequired) {
        this.dateRequired = dateRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.FROM_SUBINVENTORY_CODE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.FROM_SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getFromSubinventoryCode() {
        return fromSubinventoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.FROM_SUBINVENTORY_CODE
     *
     * @param fromSubinventoryCode the value for MTL_TXN_REQUEST_HEADERS.FROM_SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setFromSubinventoryCode(String fromSubinventoryCode) {
        this.fromSubinventoryCode = fromSubinventoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.TO_SUBINVENTORY_CODE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.TO_SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getToSubinventoryCode() {
        return toSubinventoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.TO_SUBINVENTORY_CODE
     *
     * @param toSubinventoryCode the value for MTL_TXN_REQUEST_HEADERS.TO_SUBINVENTORY_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setToSubinventoryCode(String toSubinventoryCode) {
        this.toSubinventoryCode = toSubinventoryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.TO_ACCOUNT_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.TO_ACCOUNT_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getToAccountId() {
        return toAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.TO_ACCOUNT_ID
     *
     * @param toAccountId the value for MTL_TXN_REQUEST_HEADERS.TO_ACCOUNT_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setToAccountId(BigDecimal toAccountId) {
        this.toAccountId = toAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.HEADER_STATUS
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.HEADER_STATUS
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getHeaderStatus() {
        return headerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.HEADER_STATUS
     *
     * @param headerStatus the value for MTL_TXN_REQUEST_HEADERS.HEADER_STATUS
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setHeaderStatus(BigDecimal headerStatus) {
        this.headerStatus = headerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.STATUS_DATE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.STATUS_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public Date getStatusDate() {
        return statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.STATUS_DATE
     *
     * @param statusDate the value for MTL_TXN_REQUEST_HEADERS.STATUS_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setStatusDate(Date statusDate) {
        this.statusDate = statusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATED_BY
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATED_BY
     *
     * @param lastUpdatedBy the value for MTL_TXN_REQUEST_HEADERS.LAST_UPDATED_BY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setLastUpdatedBy(BigDecimal lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_LOGIN
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_LOGIN
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getLastUpdateLogin() {
        return lastUpdateLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_LOGIN
     *
     * @param lastUpdateLogin the value for MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_LOGIN
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setLastUpdateLogin(BigDecimal lastUpdateLogin) {
        this.lastUpdateLogin = lastUpdateLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_DATE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for MTL_TXN_REQUEST_HEADERS.LAST_UPDATE_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.CREATED_BY
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.CREATED_BY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.CREATED_BY
     *
     * @param createdBy the value for MTL_TXN_REQUEST_HEADERS.CREATED_BY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setCreatedBy(BigDecimal createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.CREATION_DATE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.CREATION_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.CREATION_DATE
     *
     * @param creationDate the value for MTL_TXN_REQUEST_HEADERS.CREATION_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.REQUEST_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.REQUEST_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getRequestId() {
        return requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.REQUEST_ID
     *
     * @param requestId the value for MTL_TXN_REQUEST_HEADERS.REQUEST_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setRequestId(BigDecimal requestId) {
        this.requestId = requestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_APPLICATION_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.PROGRAM_APPLICATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getProgramApplicationId() {
        return programApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_APPLICATION_ID
     *
     * @param programApplicationId the value for MTL_TXN_REQUEST_HEADERS.PROGRAM_APPLICATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setProgramApplicationId(BigDecimal programApplicationId) {
        this.programApplicationId = programApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.PROGRAM_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getProgramId() {
        return programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_ID
     *
     * @param programId the value for MTL_TXN_REQUEST_HEADERS.PROGRAM_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setProgramId(BigDecimal programId) {
        this.programId = programId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_UPDATE_DATE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.PROGRAM_UPDATE_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public Date getProgramUpdateDate() {
        return programUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.PROGRAM_UPDATE_DATE
     *
     * @param programUpdateDate the value for MTL_TXN_REQUEST_HEADERS.PROGRAM_UPDATE_DATE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setProgramUpdateDate(Date programUpdateDate) {
        this.programUpdateDate = programUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.GROUPING_RULE_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.GROUPING_RULE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getGroupingRuleId() {
        return groupingRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.GROUPING_RULE_ID
     *
     * @param groupingRuleId the value for MTL_TXN_REQUEST_HEADERS.GROUPING_RULE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setGroupingRuleId(BigDecimal groupingRuleId) {
        this.groupingRuleId = groupingRuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE1
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE1
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE1
     *
     * @param attribute1 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE1
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE2
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE2
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE2
     *
     * @param attribute2 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE2
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE3
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE3
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE3
     *
     * @param attribute3 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE3
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE4
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE4
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE4
     *
     * @param attribute4 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE4
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE5
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE5
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE5
     *
     * @param attribute5 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE5
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE6
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE6
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute6() {
        return attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE6
     *
     * @param attribute6 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE6
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute6(String attribute6) {
        this.attribute6 = attribute6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE7
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE7
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute7() {
        return attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE7
     *
     * @param attribute7 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE7
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute7(String attribute7) {
        this.attribute7 = attribute7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE8
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE8
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute8() {
        return attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE8
     *
     * @param attribute8 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE8
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute8(String attribute8) {
        this.attribute8 = attribute8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE9
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE9
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute9() {
        return attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE9
     *
     * @param attribute9 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE9
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute9(String attribute9) {
        this.attribute9 = attribute9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE10
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE10
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute10() {
        return attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE10
     *
     * @param attribute10 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE10
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute10(String attribute10) {
        this.attribute10 = attribute10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE11
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE11
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute11() {
        return attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE11
     *
     * @param attribute11 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE11
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute11(String attribute11) {
        this.attribute11 = attribute11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE12
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE12
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute12() {
        return attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE12
     *
     * @param attribute12 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE12
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute12(String attribute12) {
        this.attribute12 = attribute12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE13
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE13
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute13() {
        return attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE13
     *
     * @param attribute13 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE13
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute13(String attribute13) {
        this.attribute13 = attribute13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE14
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE14
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute14() {
        return attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE14
     *
     * @param attribute14 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE14
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute14(String attribute14) {
        this.attribute14 = attribute14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE15
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE15
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttribute15() {
        return attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE15
     *
     * @param attribute15 the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE15
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttribute15(String attribute15) {
        this.attribute15 = attribute15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE_CATEGORY
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ATTRIBUTE_CATEGORY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAttributeCategory() {
        return attributeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ATTRIBUTE_CATEGORY
     *
     * @param attributeCategory the value for MTL_TXN_REQUEST_HEADERS.ATTRIBUTE_CATEGORY
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAttributeCategory(String attributeCategory) {
        this.attributeCategory = attributeCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.SHIP_TO_LOCATION_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.SHIP_TO_LOCATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getShipToLocationId() {
        return shipToLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.SHIP_TO_LOCATION_ID
     *
     * @param shipToLocationId the value for MTL_TXN_REQUEST_HEADERS.SHIP_TO_LOCATION_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setShipToLocationId(BigDecimal shipToLocationId) {
        this.shipToLocationId = shipToLocationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.FREIGHT_CODE
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.FREIGHT_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getFreightCode() {
        return freightCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.FREIGHT_CODE
     *
     * @param freightCode the value for MTL_TXN_REQUEST_HEADERS.FREIGHT_CODE
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setFreightCode(String freightCode) {
        this.freightCode = freightCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.SHIPMENT_METHOD
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.SHIPMENT_METHOD
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getShipmentMethod() {
        return shipmentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.SHIPMENT_METHOD
     *
     * @param shipmentMethod the value for MTL_TXN_REQUEST_HEADERS.SHIPMENT_METHOD
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setShipmentMethod(String shipmentMethod) {
        this.shipmentMethod = shipmentMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.AUTO_RECEIPT_FLAG
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.AUTO_RECEIPT_FLAG
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAutoReceiptFlag() {
        return autoReceiptFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.AUTO_RECEIPT_FLAG
     *
     * @param autoReceiptFlag the value for MTL_TXN_REQUEST_HEADERS.AUTO_RECEIPT_FLAG
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAutoReceiptFlag(String autoReceiptFlag) {
        this.autoReceiptFlag = autoReceiptFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.REFERENCE_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.REFERENCE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getReferenceId() {
        return referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.REFERENCE_ID
     *
     * @param referenceId the value for MTL_TXN_REQUEST_HEADERS.REFERENCE_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setReferenceId(BigDecimal referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.REFERENCE_DETAIL_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.REFERENCE_DETAIL_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public BigDecimal getReferenceDetailId() {
        return referenceDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.REFERENCE_DETAIL_ID
     *
     * @param referenceDetailId the value for MTL_TXN_REQUEST_HEADERS.REFERENCE_DETAIL_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setReferenceDetailId(BigDecimal referenceDetailId) {
        this.referenceDetailId = referenceDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MTL_TXN_REQUEST_HEADERS.ASSIGNMENT_ID
     *
     * @return the value of MTL_TXN_REQUEST_HEADERS.ASSIGNMENT_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public String getAssignmentId() {
        return assignmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MTL_TXN_REQUEST_HEADERS.ASSIGNMENT_ID
     *
     * @param assignmentId the value for MTL_TXN_REQUEST_HEADERS.ASSIGNMENT_ID
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    public void setAssignmentId(String assignmentId) {
        this.assignmentId = assignmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_TXN_REQUEST_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MtlTxnRequestHeaders other = (MtlTxnRequestHeaders) that;
        return (this.getHeaderId() == null ? other.getHeaderId() == null : this.getHeaderId().equals(other.getHeaderId()))
            && (this.getRequestNumber() == null ? other.getRequestNumber() == null : this.getRequestNumber().equals(other.getRequestNumber()))
            && (this.getTransactionTypeId() == null ? other.getTransactionTypeId() == null : this.getTransactionTypeId().equals(other.getTransactionTypeId()))
            && (this.getMoveOrderType() == null ? other.getMoveOrderType() == null : this.getMoveOrderType().equals(other.getMoveOrderType()))
            && (this.getOrganizationId() == null ? other.getOrganizationId() == null : this.getOrganizationId().equals(other.getOrganizationId()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getDateRequired() == null ? other.getDateRequired() == null : this.getDateRequired().equals(other.getDateRequired()))
            && (this.getFromSubinventoryCode() == null ? other.getFromSubinventoryCode() == null : this.getFromSubinventoryCode().equals(other.getFromSubinventoryCode()))
            && (this.getToSubinventoryCode() == null ? other.getToSubinventoryCode() == null : this.getToSubinventoryCode().equals(other.getToSubinventoryCode()))
            && (this.getToAccountId() == null ? other.getToAccountId() == null : this.getToAccountId().equals(other.getToAccountId()))
            && (this.getHeaderStatus() == null ? other.getHeaderStatus() == null : this.getHeaderStatus().equals(other.getHeaderStatus()))
            && (this.getStatusDate() == null ? other.getStatusDate() == null : this.getStatusDate().equals(other.getStatusDate()))
            && (this.getLastUpdatedBy() == null ? other.getLastUpdatedBy() == null : this.getLastUpdatedBy().equals(other.getLastUpdatedBy()))
            && (this.getLastUpdateLogin() == null ? other.getLastUpdateLogin() == null : this.getLastUpdateLogin().equals(other.getLastUpdateLogin()))
            && (this.getLastUpdateDate() == null ? other.getLastUpdateDate() == null : this.getLastUpdateDate().equals(other.getLastUpdateDate()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreationDate() == null ? other.getCreationDate() == null : this.getCreationDate().equals(other.getCreationDate()))
            && (this.getRequestId() == null ? other.getRequestId() == null : this.getRequestId().equals(other.getRequestId()))
            && (this.getProgramApplicationId() == null ? other.getProgramApplicationId() == null : this.getProgramApplicationId().equals(other.getProgramApplicationId()))
            && (this.getProgramId() == null ? other.getProgramId() == null : this.getProgramId().equals(other.getProgramId()))
            && (this.getProgramUpdateDate() == null ? other.getProgramUpdateDate() == null : this.getProgramUpdateDate().equals(other.getProgramUpdateDate()))
            && (this.getGroupingRuleId() == null ? other.getGroupingRuleId() == null : this.getGroupingRuleId().equals(other.getGroupingRuleId()))
            && (this.getAttribute1() == null ? other.getAttribute1() == null : this.getAttribute1().equals(other.getAttribute1()))
            && (this.getAttribute2() == null ? other.getAttribute2() == null : this.getAttribute2().equals(other.getAttribute2()))
            && (this.getAttribute3() == null ? other.getAttribute3() == null : this.getAttribute3().equals(other.getAttribute3()))
            && (this.getAttribute4() == null ? other.getAttribute4() == null : this.getAttribute4().equals(other.getAttribute4()))
            && (this.getAttribute5() == null ? other.getAttribute5() == null : this.getAttribute5().equals(other.getAttribute5()))
            && (this.getAttribute6() == null ? other.getAttribute6() == null : this.getAttribute6().equals(other.getAttribute6()))
            && (this.getAttribute7() == null ? other.getAttribute7() == null : this.getAttribute7().equals(other.getAttribute7()))
            && (this.getAttribute8() == null ? other.getAttribute8() == null : this.getAttribute8().equals(other.getAttribute8()))
            && (this.getAttribute9() == null ? other.getAttribute9() == null : this.getAttribute9().equals(other.getAttribute9()))
            && (this.getAttribute10() == null ? other.getAttribute10() == null : this.getAttribute10().equals(other.getAttribute10()))
            && (this.getAttribute11() == null ? other.getAttribute11() == null : this.getAttribute11().equals(other.getAttribute11()))
            && (this.getAttribute12() == null ? other.getAttribute12() == null : this.getAttribute12().equals(other.getAttribute12()))
            && (this.getAttribute13() == null ? other.getAttribute13() == null : this.getAttribute13().equals(other.getAttribute13()))
            && (this.getAttribute14() == null ? other.getAttribute14() == null : this.getAttribute14().equals(other.getAttribute14()))
            && (this.getAttribute15() == null ? other.getAttribute15() == null : this.getAttribute15().equals(other.getAttribute15()))
            && (this.getAttributeCategory() == null ? other.getAttributeCategory() == null : this.getAttributeCategory().equals(other.getAttributeCategory()))
            && (this.getShipToLocationId() == null ? other.getShipToLocationId() == null : this.getShipToLocationId().equals(other.getShipToLocationId()))
            && (this.getFreightCode() == null ? other.getFreightCode() == null : this.getFreightCode().equals(other.getFreightCode()))
            && (this.getShipmentMethod() == null ? other.getShipmentMethod() == null : this.getShipmentMethod().equals(other.getShipmentMethod()))
            && (this.getAutoReceiptFlag() == null ? other.getAutoReceiptFlag() == null : this.getAutoReceiptFlag().equals(other.getAutoReceiptFlag()))
            && (this.getReferenceId() == null ? other.getReferenceId() == null : this.getReferenceId().equals(other.getReferenceId()))
            && (this.getReferenceDetailId() == null ? other.getReferenceDetailId() == null : this.getReferenceDetailId().equals(other.getReferenceDetailId()))
            && (this.getAssignmentId() == null ? other.getAssignmentId() == null : this.getAssignmentId().equals(other.getAssignmentId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MTL_TXN_REQUEST_HEADERS
     *
     * @mbggenerated Thu Dec 22 16:20:30 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHeaderId() == null) ? 0 : getHeaderId().hashCode());
        result = prime * result + ((getRequestNumber() == null) ? 0 : getRequestNumber().hashCode());
        result = prime * result + ((getTransactionTypeId() == null) ? 0 : getTransactionTypeId().hashCode());
        result = prime * result + ((getMoveOrderType() == null) ? 0 : getMoveOrderType().hashCode());
        result = prime * result + ((getOrganizationId() == null) ? 0 : getOrganizationId().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getDateRequired() == null) ? 0 : getDateRequired().hashCode());
        result = prime * result + ((getFromSubinventoryCode() == null) ? 0 : getFromSubinventoryCode().hashCode());
        result = prime * result + ((getToSubinventoryCode() == null) ? 0 : getToSubinventoryCode().hashCode());
        result = prime * result + ((getToAccountId() == null) ? 0 : getToAccountId().hashCode());
        result = prime * result + ((getHeaderStatus() == null) ? 0 : getHeaderStatus().hashCode());
        result = prime * result + ((getStatusDate() == null) ? 0 : getStatusDate().hashCode());
        result = prime * result + ((getLastUpdatedBy() == null) ? 0 : getLastUpdatedBy().hashCode());
        result = prime * result + ((getLastUpdateLogin() == null) ? 0 : getLastUpdateLogin().hashCode());
        result = prime * result + ((getLastUpdateDate() == null) ? 0 : getLastUpdateDate().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreationDate() == null) ? 0 : getCreationDate().hashCode());
        result = prime * result + ((getRequestId() == null) ? 0 : getRequestId().hashCode());
        result = prime * result + ((getProgramApplicationId() == null) ? 0 : getProgramApplicationId().hashCode());
        result = prime * result + ((getProgramId() == null) ? 0 : getProgramId().hashCode());
        result = prime * result + ((getProgramUpdateDate() == null) ? 0 : getProgramUpdateDate().hashCode());
        result = prime * result + ((getGroupingRuleId() == null) ? 0 : getGroupingRuleId().hashCode());
        result = prime * result + ((getAttribute1() == null) ? 0 : getAttribute1().hashCode());
        result = prime * result + ((getAttribute2() == null) ? 0 : getAttribute2().hashCode());
        result = prime * result + ((getAttribute3() == null) ? 0 : getAttribute3().hashCode());
        result = prime * result + ((getAttribute4() == null) ? 0 : getAttribute4().hashCode());
        result = prime * result + ((getAttribute5() == null) ? 0 : getAttribute5().hashCode());
        result = prime * result + ((getAttribute6() == null) ? 0 : getAttribute6().hashCode());
        result = prime * result + ((getAttribute7() == null) ? 0 : getAttribute7().hashCode());
        result = prime * result + ((getAttribute8() == null) ? 0 : getAttribute8().hashCode());
        result = prime * result + ((getAttribute9() == null) ? 0 : getAttribute9().hashCode());
        result = prime * result + ((getAttribute10() == null) ? 0 : getAttribute10().hashCode());
        result = prime * result + ((getAttribute11() == null) ? 0 : getAttribute11().hashCode());
        result = prime * result + ((getAttribute12() == null) ? 0 : getAttribute12().hashCode());
        result = prime * result + ((getAttribute13() == null) ? 0 : getAttribute13().hashCode());
        result = prime * result + ((getAttribute14() == null) ? 0 : getAttribute14().hashCode());
        result = prime * result + ((getAttribute15() == null) ? 0 : getAttribute15().hashCode());
        result = prime * result + ((getAttributeCategory() == null) ? 0 : getAttributeCategory().hashCode());
        result = prime * result + ((getShipToLocationId() == null) ? 0 : getShipToLocationId().hashCode());
        result = prime * result + ((getFreightCode() == null) ? 0 : getFreightCode().hashCode());
        result = prime * result + ((getShipmentMethod() == null) ? 0 : getShipmentMethod().hashCode());
        result = prime * result + ((getAutoReceiptFlag() == null) ? 0 : getAutoReceiptFlag().hashCode());
        result = prime * result + ((getReferenceId() == null) ? 0 : getReferenceId().hashCode());
        result = prime * result + ((getReferenceDetailId() == null) ? 0 : getReferenceDetailId().hashCode());
        result = prime * result + ((getAssignmentId() == null) ? 0 : getAssignmentId().hashCode());
        return result;
    }
}