package com.egdfrm.core.model.standard;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class TtApplicationUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.LOGIN_NAME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String loginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.SALT
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String salt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.USER_NAME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.USER_PHONE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.USER_M_PHOME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String userMPhome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.USER_EMAIL
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.USER_STATUS
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.CREATE_BY
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.CREATE_DATE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.UPDATE_BY
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.UPDATE_DATE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.SUPPLIER_ID
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private BigDecimal supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.BARCODE_STR
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String barcodeStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.USER_ID
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.PLAN_LINE_CODE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String planLineCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TT_APPLICATION_USER.DEPT_CODE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TT_APPLICATION_USER
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.LOGIN_NAME
     *
     * @return the value of TT_APPLICATION_USER.LOGIN_NAME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.LOGIN_NAME
     *
     * @param loginName the value for TT_APPLICATION_USER.LOGIN_NAME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @return the value of TT_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @param loginPassword the value for TT_APPLICATION_USER.LOGIN_PASSWORD
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.SALT
     *
     * @return the value of TT_APPLICATION_USER.SALT
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.SALT
     *
     * @param salt the value for TT_APPLICATION_USER.SALT
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.USER_NAME
     *
     * @return the value of TT_APPLICATION_USER.USER_NAME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.USER_NAME
     *
     * @param userName the value for TT_APPLICATION_USER.USER_NAME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.USER_PHONE
     *
     * @return the value of TT_APPLICATION_USER.USER_PHONE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.USER_PHONE
     *
     * @param userPhone the value for TT_APPLICATION_USER.USER_PHONE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.USER_M_PHOME
     *
     * @return the value of TT_APPLICATION_USER.USER_M_PHOME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getUserMPhome() {
        return userMPhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.USER_M_PHOME
     *
     * @param userMPhome the value for TT_APPLICATION_USER.USER_M_PHOME
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUserMPhome(String userMPhome) {
        this.userMPhome = userMPhome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.USER_EMAIL
     *
     * @return the value of TT_APPLICATION_USER.USER_EMAIL
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.USER_EMAIL
     *
     * @param userEmail the value for TT_APPLICATION_USER.USER_EMAIL
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.USER_STATUS
     *
     * @return the value of TT_APPLICATION_USER.USER_STATUS
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.USER_STATUS
     *
     * @param userStatus the value for TT_APPLICATION_USER.USER_STATUS
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.CREATE_BY
     *
     * @return the value of TT_APPLICATION_USER.CREATE_BY
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.CREATE_BY
     *
     * @param createBy the value for TT_APPLICATION_USER.CREATE_BY
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.CREATE_DATE
     *
     * @return the value of TT_APPLICATION_USER.CREATE_DATE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.CREATE_DATE
     *
     * @param createDate the value for TT_APPLICATION_USER.CREATE_DATE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.UPDATE_BY
     *
     * @return the value of TT_APPLICATION_USER.UPDATE_BY
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.UPDATE_BY
     *
     * @param updateBy the value for TT_APPLICATION_USER.UPDATE_BY
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.UPDATE_DATE
     *
     * @return the value of TT_APPLICATION_USER.UPDATE_DATE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.UPDATE_DATE
     *
     * @param updateDate the value for TT_APPLICATION_USER.UPDATE_DATE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.SUPPLIER_ID
     *
     * @return the value of TT_APPLICATION_USER.SUPPLIER_ID
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public BigDecimal getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.SUPPLIER_ID
     *
     * @param supplierId the value for TT_APPLICATION_USER.SUPPLIER_ID
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setSupplierId(BigDecimal supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.BARCODE_STR
     *
     * @return the value of TT_APPLICATION_USER.BARCODE_STR
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getBarcodeStr() {
        return barcodeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.BARCODE_STR
     *
     * @param barcodeStr the value for TT_APPLICATION_USER.BARCODE_STR
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setBarcodeStr(String barcodeStr) {
        this.barcodeStr = barcodeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.USER_ID
     *
     * @return the value of TT_APPLICATION_USER.USER_ID
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.USER_ID
     *
     * @param userId the value for TT_APPLICATION_USER.USER_ID
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.PLAN_LINE_CODE
     *
     * @return the value of TT_APPLICATION_USER.PLAN_LINE_CODE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getPlanLineCode() {
        return planLineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.PLAN_LINE_CODE
     *
     * @param planLineCode the value for TT_APPLICATION_USER.PLAN_LINE_CODE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setPlanLineCode(String planLineCode) {
        this.planLineCode = planLineCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TT_APPLICATION_USER.DEPT_CODE
     *
     * @return the value of TT_APPLICATION_USER.DEPT_CODE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TT_APPLICATION_USER.DEPT_CODE
     *
     * @param deptCode the value for TT_APPLICATION_USER.DEPT_CODE
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_APPLICATION_USER
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TtApplicationUser other = (TtApplicationUser) that;
        return (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getLoginPassword() == null ? other.getLoginPassword() == null : this.getLoginPassword().equals(other.getLoginPassword()))
            && (this.getSalt() == null ? other.getSalt() == null : this.getSalt().equals(other.getSalt()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
            && (this.getUserMPhome() == null ? other.getUserMPhome() == null : this.getUserMPhome().equals(other.getUserMPhome()))
            && (this.getUserEmail() == null ? other.getUserEmail() == null : this.getUserEmail().equals(other.getUserEmail()))
            && (this.getUserStatus() == null ? other.getUserStatus() == null : this.getUserStatus().equals(other.getUserStatus()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getSupplierId() == null ? other.getSupplierId() == null : this.getSupplierId().equals(other.getSupplierId()))
            && (this.getBarcodeStr() == null ? other.getBarcodeStr() == null : this.getBarcodeStr().equals(other.getBarcodeStr()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getPlanLineCode() == null ? other.getPlanLineCode() == null : this.getPlanLineCode().equals(other.getPlanLineCode()))
            && (this.getDeptCode() == null ? other.getDeptCode() == null : this.getDeptCode().equals(other.getDeptCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_APPLICATION_USER
     *
     * @mbggenerated Wed Dec 28 12:11:08 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getLoginPassword() == null) ? 0 : getLoginPassword().hashCode());
        result = prime * result + ((getSalt() == null) ? 0 : getSalt().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getUserMPhome() == null) ? 0 : getUserMPhome().hashCode());
        result = prime * result + ((getUserEmail() == null) ? 0 : getUserEmail().hashCode());
        result = prime * result + ((getUserStatus() == null) ? 0 : getUserStatus().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getSupplierId() == null) ? 0 : getSupplierId().hashCode());
        result = prime * result + ((getBarcodeStr() == null) ? 0 : getBarcodeStr().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getPlanLineCode() == null) ? 0 : getPlanLineCode().hashCode());
        result = prime * result + ((getDeptCode() == null) ? 0 : getDeptCode().hashCode());
        return result;
    } 
	public String getRoleCode() {
		return roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}
	private String roleCode;
}