package com.egdfrm.core.mapper.standard;

import com.egdfrm.core.model.standard.MdSupplier;
import com.egdfrm.core.model.standard.MdSupplierCriteria;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MdSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int countByExample(MdSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int deleteByExample(MdSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int deleteByPrimaryKey(BigDecimal supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int insert(MdSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int insertSelective(MdSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    List<MdSupplier> selectByExample(MdSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    MdSupplier selectByPrimaryKey(BigDecimal supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int updateByExampleSelective(@Param("record") MdSupplier record, @Param("example") MdSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int updateByExample(@Param("record") MdSupplier record, @Param("example") MdSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int updateByPrimaryKeySelective(MdSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_SUPPLIER
     *
     * @mbggenerated Tue Sep 22 18:01:59 CST 2015
     */
    int updateByPrimaryKey(MdSupplier record);
}