package com.egdfrm.core.mapper.standard;

import com.egdfrm.core.model.standard.TtUserRole;
import com.egdfrm.core.model.standard.TtUserRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TtUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Mon Mar 28 15:47:43 CST 2016
     */
    int countByExample(TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Mon Mar 28 15:47:43 CST 2016
     */
    int deleteByExample(TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Mon Mar 28 15:47:43 CST 2016
     */
    int insert(TtUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Mon Mar 28 15:47:43 CST 2016
     */
    int insertSelective(TtUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Mon Mar 28 15:47:43 CST 2016
     */
    List<TtUserRole> selectByExample(TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Mon Mar 28 15:47:43 CST 2016
     */
    int updateByExampleSelective(@Param("record") TtUserRole record, @Param("example") TtUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TT_USER_ROLE
     *
     * @mbggenerated Mon Mar 28 15:47:43 CST 2016
     */
    int updateByExample(@Param("record") TtUserRole record, @Param("example") TtUserRoleCriteria example);
}