package com.egdfrm.extend.model.standard;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MdCategoryVCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public MdCategoryVCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("CATEGORY_ID is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("CATEGORY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(BigDecimal value) {
            addCriterion("CATEGORY_ID =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(BigDecimal value) {
            addCriterion("CATEGORY_ID <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(BigDecimal value) {
            addCriterion("CATEGORY_ID >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CATEGORY_ID >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(BigDecimal value) {
            addCriterion("CATEGORY_ID <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CATEGORY_ID <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<BigDecimal> values) {
            addCriterion("CATEGORY_ID in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<BigDecimal> values) {
            addCriterion("CATEGORY_ID not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CATEGORY_ID between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CATEGORY_ID not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("CREATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("CREATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(BigDecimal value) {
            addCriterion("CREATE_BY =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(BigDecimal value) {
            addCriterion("CREATE_BY <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(BigDecimal value) {
            addCriterion("CREATE_BY >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_BY >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(BigDecimal value) {
            addCriterion("CREATE_BY <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CREATE_BY <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<BigDecimal> values) {
            addCriterion("CREATE_BY in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<BigDecimal> values) {
            addCriterion("CREATE_BY not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_BY between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CREATE_BY not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("UPDATE_BY is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("UPDATE_BY is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(BigDecimal value) {
            addCriterion("UPDATE_BY =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(BigDecimal value) {
            addCriterion("UPDATE_BY <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(BigDecimal value) {
            addCriterion("UPDATE_BY >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("UPDATE_BY >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(BigDecimal value) {
            addCriterion("UPDATE_BY <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(BigDecimal value) {
            addCriterion("UPDATE_BY <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<BigDecimal> values) {
            addCriterion("UPDATE_BY in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<BigDecimal> values) {
            addCriterion("UPDATE_BY not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPDATE_BY between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("UPDATE_BY not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNull() {
            addCriterion("UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIsNotNull() {
            addCriterion("UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDateEqualTo(Date value) {
            addCriterion("UPDATE_DATE =", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotEqualTo(Date value) {
            addCriterion("UPDATE_DATE <>", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThan(Date value) {
            addCriterion("UPDATE_DATE >", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE >=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThan(Date value) {
            addCriterion("UPDATE_DATE <", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_DATE <=", value, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateIn(List<Date> values) {
            addCriterion("UPDATE_DATE in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotIn(List<Date> values) {
            addCriterion("UPDATE_DATE not in", values, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_DATE not between", value1, value2, "updateDate");
            return (Criteria) this;
        }

        public Criteria andBigCategoryIsNull() {
            addCriterion("BIG_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andBigCategoryIsNotNull() {
            addCriterion("BIG_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andBigCategoryEqualTo(String value) {
            addCriterion("BIG_CATEGORY =", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryNotEqualTo(String value) {
            addCriterion("BIG_CATEGORY <>", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryGreaterThan(String value) {
            addCriterion("BIG_CATEGORY >", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("BIG_CATEGORY >=", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryLessThan(String value) {
            addCriterion("BIG_CATEGORY <", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryLessThanOrEqualTo(String value) {
            addCriterion("BIG_CATEGORY <=", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryLike(String value) {
            addCriterion("BIG_CATEGORY like", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryNotLike(String value) {
            addCriterion("BIG_CATEGORY not like", value, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryIn(List<String> values) {
            addCriterion("BIG_CATEGORY in", values, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryNotIn(List<String> values) {
            addCriterion("BIG_CATEGORY not in", values, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryBetween(String value1, String value2) {
            addCriterion("BIG_CATEGORY between", value1, value2, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryNotBetween(String value1, String value2) {
            addCriterion("BIG_CATEGORY not between", value1, value2, "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningIsNull() {
            addCriterion("BIG_CATEGORY_MEANING is null");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningIsNotNull() {
            addCriterion("BIG_CATEGORY_MEANING is not null");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningEqualTo(String value) {
            addCriterion("BIG_CATEGORY_MEANING =", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningNotEqualTo(String value) {
            addCriterion("BIG_CATEGORY_MEANING <>", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningGreaterThan(String value) {
            addCriterion("BIG_CATEGORY_MEANING >", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningGreaterThanOrEqualTo(String value) {
            addCriterion("BIG_CATEGORY_MEANING >=", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningLessThan(String value) {
            addCriterion("BIG_CATEGORY_MEANING <", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningLessThanOrEqualTo(String value) {
            addCriterion("BIG_CATEGORY_MEANING <=", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningLike(String value) {
            addCriterion("BIG_CATEGORY_MEANING like", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningNotLike(String value) {
            addCriterion("BIG_CATEGORY_MEANING not like", value, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningIn(List<String> values) {
            addCriterion("BIG_CATEGORY_MEANING in", values, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningNotIn(List<String> values) {
            addCriterion("BIG_CATEGORY_MEANING not in", values, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningBetween(String value1, String value2) {
            addCriterion("BIG_CATEGORY_MEANING between", value1, value2, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningNotBetween(String value1, String value2) {
            addCriterion("BIG_CATEGORY_MEANING not between", value1, value2, "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryIsNull() {
            addCriterion("MIDDLE_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryIsNotNull() {
            addCriterion("MIDDLE_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY =", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryNotEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY <>", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryGreaterThan(String value) {
            addCriterion("MIDDLE_CATEGORY >", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY >=", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryLessThan(String value) {
            addCriterion("MIDDLE_CATEGORY <", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryLessThanOrEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY <=", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryLike(String value) {
            addCriterion("MIDDLE_CATEGORY like", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryNotLike(String value) {
            addCriterion("MIDDLE_CATEGORY not like", value, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryIn(List<String> values) {
            addCriterion("MIDDLE_CATEGORY in", values, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryNotIn(List<String> values) {
            addCriterion("MIDDLE_CATEGORY not in", values, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryBetween(String value1, String value2) {
            addCriterion("MIDDLE_CATEGORY between", value1, value2, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryNotBetween(String value1, String value2) {
            addCriterion("MIDDLE_CATEGORY not between", value1, value2, "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningIsNull() {
            addCriterion("MIDDLE_CATEGORY_MEANING is null");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningIsNotNull() {
            addCriterion("MIDDLE_CATEGORY_MEANING is not null");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING =", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningNotEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING <>", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningGreaterThan(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING >", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningGreaterThanOrEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING >=", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningLessThan(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING <", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningLessThanOrEqualTo(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING <=", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningLike(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING like", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningNotLike(String value) {
            addCriterion("MIDDLE_CATEGORY_MEANING not like", value, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningIn(List<String> values) {
            addCriterion("MIDDLE_CATEGORY_MEANING in", values, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningNotIn(List<String> values) {
            addCriterion("MIDDLE_CATEGORY_MEANING not in", values, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningBetween(String value1, String value2) {
            addCriterion("MIDDLE_CATEGORY_MEANING between", value1, value2, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningNotBetween(String value1, String value2) {
            addCriterion("MIDDLE_CATEGORY_MEANING not between", value1, value2, "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryIsNull() {
            addCriterion("SMALL_CATEGORY is null");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryIsNotNull() {
            addCriterion("SMALL_CATEGORY is not null");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryEqualTo(String value) {
            addCriterion("SMALL_CATEGORY =", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryNotEqualTo(String value) {
            addCriterion("SMALL_CATEGORY <>", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryGreaterThan(String value) {
            addCriterion("SMALL_CATEGORY >", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("SMALL_CATEGORY >=", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryLessThan(String value) {
            addCriterion("SMALL_CATEGORY <", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryLessThanOrEqualTo(String value) {
            addCriterion("SMALL_CATEGORY <=", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryLike(String value) {
            addCriterion("SMALL_CATEGORY like", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryNotLike(String value) {
            addCriterion("SMALL_CATEGORY not like", value, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryIn(List<String> values) {
            addCriterion("SMALL_CATEGORY in", values, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryNotIn(List<String> values) {
            addCriterion("SMALL_CATEGORY not in", values, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryBetween(String value1, String value2) {
            addCriterion("SMALL_CATEGORY between", value1, value2, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryNotBetween(String value1, String value2) {
            addCriterion("SMALL_CATEGORY not between", value1, value2, "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningIsNull() {
            addCriterion("SMALL_CATEGORY_MEANING is null");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningIsNotNull() {
            addCriterion("SMALL_CATEGORY_MEANING is not null");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningEqualTo(String value) {
            addCriterion("SMALL_CATEGORY_MEANING =", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningNotEqualTo(String value) {
            addCriterion("SMALL_CATEGORY_MEANING <>", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningGreaterThan(String value) {
            addCriterion("SMALL_CATEGORY_MEANING >", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningGreaterThanOrEqualTo(String value) {
            addCriterion("SMALL_CATEGORY_MEANING >=", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningLessThan(String value) {
            addCriterion("SMALL_CATEGORY_MEANING <", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningLessThanOrEqualTo(String value) {
            addCriterion("SMALL_CATEGORY_MEANING <=", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningLike(String value) {
            addCriterion("SMALL_CATEGORY_MEANING like", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningNotLike(String value) {
            addCriterion("SMALL_CATEGORY_MEANING not like", value, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningIn(List<String> values) {
            addCriterion("SMALL_CATEGORY_MEANING in", values, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningNotIn(List<String> values) {
            addCriterion("SMALL_CATEGORY_MEANING not in", values, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningBetween(String value1, String value2) {
            addCriterion("SMALL_CATEGORY_MEANING between", value1, value2, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningNotBetween(String value1, String value2) {
            addCriterion("SMALL_CATEGORY_MEANING not between", value1, value2, "smallCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andBigCategoryLikeInsensitive(String value) {
            addCriterion("upper(BIG_CATEGORY) like", value.toUpperCase(), "bigCategory");
            return (Criteria) this;
        }

        public Criteria andBigCategoryMeaningLikeInsensitive(String value) {
            addCriterion("upper(BIG_CATEGORY_MEANING) like", value.toUpperCase(), "bigCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryLikeInsensitive(String value) {
            addCriterion("upper(MIDDLE_CATEGORY) like", value.toUpperCase(), "middleCategory");
            return (Criteria) this;
        }

        public Criteria andMiddleCategoryMeaningLikeInsensitive(String value) {
            addCriterion("upper(MIDDLE_CATEGORY_MEANING) like", value.toUpperCase(), "middleCategoryMeaning");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryLikeInsensitive(String value) {
            addCriterion("upper(SMALL_CATEGORY) like", value.toUpperCase(), "smallCategory");
            return (Criteria) this;
        }

        public Criteria andSmallCategoryMeaningLikeInsensitive(String value) {
            addCriterion("upper(SMALL_CATEGORY_MEANING) like", value.toUpperCase(), "smallCategoryMeaning");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 03 17:23:02 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MD_CATEGORY_V
     *
     * @mbggenerated Fri Jun 03 17:23:02 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}